### ISSUE TITLE
 bigger than but smaller than ROCP value(range)?

### ISSUE THREAD

**Issue by kiandp** [freqtrade/freqtrade-strategies#101]
## Step 1: What indicators are required?
ROCP(RATE OF CHANGE PERCENTAGE)

##question?
How can I range this ROCP and use it in my buy indicators?
I mean:
"        dataframe['rocp']=ta.ROCP(dataframe,timeperiod=5)  "
&
"( -0.03<dataframe['rocp']<0.03),but it gives me an error and then i can't do it this way
"(dataframe['rocp']<0.03) & (dataframe['rocp']>-0.03)"
Cause the meaning will change completely. 

. How can I define "Bigger than but smaller than" on my buy or Sell indicator?

**Comment by xmatthias** [comment]
Please use code blocks for code. (tripple "`")

The code above is formatted in a way that makes it impossible to detect eventual syntax errors.

You mention "gives me an error" - please include the error, otherwise we'll be unable to help you.

**Comment by kiandp** [comment]
This is the code I used for my buy signal:
             
   """ (dataframe['ema9'] > dataframe['ema21'])&
          ( -0.03<dataframe['rocp']<0.03)"""
And here is the error":
""""
"2020-09-27 10:40:10,861 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/sirdp/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/sirdp/freqtrade/freqtrade/commands/optimize_commands.py", line 49, in start_backtesting
    backtesting.start()
  File "/home/sirdp/freqtrade/freqtrade/optimize/backtesting.py", line 412, in start
    position_stacking=position_stacking,
  File "/home/sirdp/freqtrade/freqtrade/optimize/backtesting.py", line 308, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/home/sirdp/freqtrade/freqtrade/optimize/backtesting.py", line 162, in _get_ohlcv_as_lists
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/home/sirdp/freqtrade/freqtrade/strategy/interface.py", line 625, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/home/sirdp/freqtrade/user_data/strategies/hustle.py", line 193, in populate_buy_trend
    'buy'] = 1
  File "/home/sirdp/freqtrade/.env/lib/python3.6/site-packages/pandas/core/generic.py", line 1327, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
""""
I think I can't use this function this way""" ( -0.03<dataframe['rocp']<0.03)""" :(,  how can I use it in freqtrade ?

**Comment by xmatthias** [comment]
i suspect ROCP does not return a single series, but a dataframe (so your column `dataframe['rocp']` contains a full dataframe.

Best look at the documentation for this indicator to find out what it returns - and assign each series you need manually (it's most likely similar to the macd examples we have).

**Comment by kiandp** [comment]
@xmatthias Thanks for your insights and help.
The problem I have is about the implementation of  (a<"Bigger than but smaller than"<b) this function.
This line of code also gives me the same error because of misusing this function.
"""(dataframe['ema9'] > **dataframe['ema21'])&**
                    _**( 20<dataframe['rsi']<40)**_"""

Should is use "if  20 < dataframe['rsi'] < 40" isntead of """(  20<dataframe['rsi']<40)""".
How can I use it in my buy signal?
Thanks

**Comment by xmatthias** [comment]
well `( 20<dataframe['rsi']<40)` is equivalent to
`( 20<dataframe['rsi']) &  ( dataframe['rsi'] < 40)`.

But this is very simple pandas syntax. Please use google. 
These questions sound like you're just asking, and not even trying to solve the problem yourself - which is something i utterly hate.

**Comment by kiandp** [comment]
I understand the equation you mentioned is equivalent to the equation I asked. but having the range instead defining 2 different limits is handier & can save you time for further complex calculations.
My objection is to define a range for our dataframe.
So here the link for this question:

https://stackoverflow.com/questions/20308588/is-there-a-greater-than-but-less-than-function-in-python
But I want to deploy it in my buy strategy.
Thanks

**Comment by xmatthias** [comment]
nothing above mentions a range in this form up to this post (also something between 20 and 40 is a range).

As mentioned above, pandas does allow many things, best search for what you're trying to do in combination wiht "pandas".

**Comment by kiandp** [comment]
@xmatthias thanks for your time and response.
