### ISSUE TITLE
LINEAR REGRESSION SLOPE & LINEAR REGRESSION ANGLE range?

### ISSUE THREAD

**Issue by kiandp** [freqtrade/freqtrade-strategies#102]
*For requestion a new strategy. Please use the template below.*  
*Any strategy request that does not follow the template will be closed.*

## Step 1: What indicators are required?
LINEAR REGRESSION SLOPE & LINEAR REGRESSION ANGLE?

## Step 2: Explain the Buy Strategy
We will buy when LINEAR REGRESSION SLOP('ema20') is positive & also LINEAR REGRESSION ANGLE('ema50) is positive & also rsi slope is positive.

## Step 1: Explain the Sell Strategy
We will sell when LINEAR REGRESSION SLOP('ema20') is negative & also LINEAR REGRESSION ANGLE('ema50) is negative & also rsi_slop is negative?

## QUESTION?
I know this question might be out of the scope of freqtrade, but because freqtrade is a knowledgeable community I also wanted to ask here.
Does anyone knows what is the  range_value for "LINEAR REGRESSION ANGLE" & "LINEAR REGRESSION SLOPE" in ta_lib, does it goes a negative degree & slope when the degree and slop become negative?
  Is the  "LINEAR REGRESSION SLOPE" degree from -100 to 100?
  What about the  "LINEAR REGRESSION ANGLE"?(0 TO 360 OR IT goes reversal?)
I want to calculate [RSI_SLOP] and was able to do it but I am lagging conceptually about these 2 statistic functions?
 
& also does this LINEAR REGRESSION SLOPE the only slop available to use in our strategy? 

All ideas and insights are appreciated.
Thanks

**Comment by xmatthias** [comment]
For your question - i would recommend to ask questions related to ta-lib in the [ta-lib python](https://github.com/mrjbq7/ta-lib) repository.

They are very knowledgeble and might be the best to answer this question.

Also - you may want to simply investigate the output of an indicator by looking at the values it outputs in a [interactive environment](https://www.freqtrade.io/en/latest/strategy_analysis_example/).
You can then visualize the column - look at min / max values ... that should give you all the tools you need to answer this question yourself.

---

your Buy / sell strategy is not clear to me.
would you calculate the EMA on the linear regression slope, or is it a comparison between the slope and the EMA?
(obviously the same for angle).

**Comment by kiandp** [comment]
@xmatthias Buy signal is given based on the linear regression slope of EMA. If you look at the chart in the trading view, the Exponential moving average line is positive and going upward in an uptrend market(however it is subject to change based on which ema we are using) and in a downtrend, the ema line is going down with a negative slope.
I want to use that slope as the tradingview shows us?
For example for EMA=20, we will buy when the ema line goes up(positive slope) and sell when this line goes downward(negative slope). However, this is only one of the many signals we will use in our strategy and we can't rely solely on this signal in our strategy.
But how can I code that and use it in my strategy in the right way?
Simply I want the same slop as the tradingview is giving us and convert it to the code and use it!
Thanks

**Comment by kiandp** [comment]
@xmatthias Thanks
