### ISSUE TITLE
How to measure the slope for OBV(on balance volume)?

### ISSUE THREAD

**Issue by kiandp** [freqtrade/freqtrade-strategies#103]
I am trying to use "obv" in my strategy but since the obv indicator y_axis is not giving you valuable pieces of information, we need to measure the slope in order to detect the up or downtrend.
I tried to use the OBV slope with linear regression in ta_lib as documented, but the results are different from what I am expecting.
Can someone please help me to set the right slope for this indicator?
In addition to my question, I am looking for a trend_indicator for "OBV".
Thanks

https://www.quantopian.com/posts/help-with-talib-linear-regression

**Comment by xmatthias** [comment]
sorry for the late response - however i'm not sure i understand the issue.

according to the link, you should just be able to run the following to get what you need.

Now to be honest - i never used OBV (nor Linearreg) - 

``` python
dataframe['OBV'] = ta.OBV(dataframe)
dataframe['OBVTrend'] = ta.LINEARREG(dataframe['OBV'])
dataframe['OBVSlope'] = ta.LINEARREG_SLOPE(dataframe['OBV'])
```

However: 
If you need further support, i'd recommend to check out the [ta-lib repository](https://github.com/mrjbq7/ta-lib) - they are the real experts when it comes to using ta-lib ...

**Comment by kiandp** [comment]
@xmatthias Thanks for your time and effort.
