### ISSUE TITLE
Issue with ReinforcedSmoothScalp strategy

### ISSUE THREAD

**Issue by martemisia** [freqtrade/freqtrade-strategies#109]
When I try to start backtesting, I get this message 
KeyError: 'resample_sma'
I cannot figure out where this parameter is defined. Or where should it be defined.
Thanks for any advices.

**Comment by qmzik** [comment]
I have the same issue

**Comment by IvanResh** [comment]
Same problem here

**Comment by martemisia** [comment]
Now it works. Thanks a lot.
