### ISSUE TITLE
Using "Traders Dynamic Index (TDI)" in the strategy.

### ISSUE THREAD

**Issue by kiandp** [freqtrade/freqtrade-strategies#110]
*For requestion a new strategy. Please use the template below.*  
*Any strategy request that does not follow the template will be closed.*

## Step 1: What indicators are required?
Traders Dynamic Index (TDI)
## Step 2: Explain the Buy Strategy
I am trying to implement this indicator in freqtrade however I am not able to load it in my indicators and it gives me an error.
This indicator is in qtpylib dictionary and I have loaded to jupyter with no problem, but I can't deploy it on freqtrade.
Here are all the ways I tried to load the indicator:
1-"""dataframe['tdi'] = qtpylib.tdi(dataframe, rsi_lookback=13, rsi_smooth_len=2,
        rsi_signal_len=7, bb_lookback=34, bb_std=1.6185)"""
2-"""dataframe['tdi'] = qtpylib.tdi(qtpylib.typical_price(dataframe)"""
3-"""dataframe['tdi'] = qtpylib.tdi(qtpylib.typical_price(dataframe,rsi_lookback=13, rsi_smooth_len=2,
        rsi_signal_len=7, bb_lookback=34, bb_std=1.6185)
None of these method worked!
Please help me to load this indicator into freqtrade.
Thanks

## Source
What come from this strategy? 
https://qtpylib.io/docs/latest/indicators.html?highlight=zscore#traders-dynamic-index-tdi

**Comment by xmatthias** [comment]
well this doesn't return a series, but 6 series (the qtpylib documentation sems to be wrong ...)

you should be able to use this somehow like this (this is conceptual code ... will need your parameters ...)

``` python
tdi =  qtpylib.tdi(dataframe, rsi_lookback=13, ...)
dataframe['rsi'] = tdi['rsi']
dataframe['rsi_signal'] = tdi['rsi_signal']
dataframe['rsi_smooth'] = tdi['rsi_smooth']
dataframe['rsi_bb_upper'] = tdi['rsi_bb_upper']
dataframe['rsi_bb_lower'] = tdi['rsi_bb_lower']
dataframe['rsi_bb_mid'] = tdi['rsi_bb_mid']

...
```

**Comment by kiandp** [comment]
@xmatthias  Thanks for your fast response.

This code worked on freqtrade:
"""        tdi =  qtpylib.tdi(dataframe['close'],  rsi_lookback=13, rsi_smooth_len=2,
        rsi_signal_len=7, bb_lookback=34, bb_std=1.6185)"""
However , I can't use  ['rsi_bb_upper'],['rsi_bb_lower'],tdi['rsi_bb_mid'] in my strategy, When i use them i get no trades as a result for backtesting.
But the ['rsi_signal'] and ['rsi_smooth'] works properly.
I don't know why This is happening!
I tried this code for my sell indicator:
""" dataframe['close'] > dataframe['rsi_bb_upper']"""
After using this code in my sell indicator, surprisingly  I got zero trades.
I might be missing something here.
please help me.
Thanks for helping out,.

**Comment by xmatthias** [comment]
well this is the RSI Bollingerband (calculated from RSI, not from a price), not the "real" bollinger band

comparing it to "close" will not work / only work at random if a coin's price is between 0 and 100.

**Comment by kiandp** [comment]
@xmatthias Thanks for your clear explanation.
