### ISSUE TITLE
hyperopt file strategy CombinedBinHAndCluc

### ISSUE THREAD

**Issue by mathias5986** [freqtrade/freqtrade-strategies#111]
Hello guys,

Has anyone of you already created a hyperopt optimization file for the strategy CombinedBinHAndCluc?
Should I actually use a '--strategy (strategy) **--hyperopt**  --hyperopt-loss" in the code  to optimize the strategy?
Or can I leave the hyperopt file empty with only the 'populate_buy_trend' and 'populate_sell_trend' filled in ? 

Thanks!

Mathias

**Comment by xmatthias** [comment]
it depends, if you only want to optimize roi / stoploss, you can use an empty Hyperopt file.

To optimize buy / sell signals, you'll obviously need to have the appropriate generators and spaces.

**Comment by mathias5986** [comment]
Yes I would only like to optimize the stop loss and ROI.

**Comment by mathias5986** [comment]
Should this work ?

# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement

# --- Do not remove these libs ---
from functools import reduce
from typing import Any, Callable, Dict, List

import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame
from skopt.space import Categorical, Dimension, Integer, Real  # noqa

from freqtrade.optimize.hyperopt_interface import IHyperOpt

# --------------------------------
# Add your lib to import here
import talib.abstract as ta  # noqa
import freqtrade.vendor.qtpylib.indicators as qtpylib


class MyCoolHyperopt(IHyperOpt):

    @staticmethod
    def buy_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the buy strategy parameters to be used by Hyperopt.
        """
        def populate_buy_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Buy strategy Hyperopt will build and use.
            """
            conditions = []

            # Check that the candle had volume
            conditions.append(dataframe['volume'] > 0)

            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'buy'] = 1

            return dataframe

        return populate_buy_trend

    @staticmethod
    def indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching buy strategy parameters.
        """
        return []

    @staticmethod
    def sell_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the sell strategy parameters to be used by Hyperopt.
        """
        def populate_sell_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Sell strategy Hyperopt will build and use.
            """
            conditions = []

            # Check that the candle had volume
            conditions.append(dataframe['volume'] > 0)

            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'sell'] = 1

            return dataframe

        return populate_sell_trend

    @staticmethod
    def sell_indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching sell strategy parameters.
        """
        return []

**Comment by xmatthias** [comment]
as long as you use `--space roi stoploss` - it should be fine.

**Comment by mathias5986** [comment]
Thank you, Matthias!
