### ISSUE TITLE
i'get allways this backtesting warnings

### ISSUE THREAD

**Issue by nodwan** [freqtrade/freqtrade-strategies#113]
021-01-12 13:08:12,795 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy Strategy001
2021-01-12 13:08:22,911 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2020-12-11 17:00:00 up to 2021-01-12 07:50:00 (31 days)..
/home/pi/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
/home/pi/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexing.py:1719: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
/home/pi/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexing.py:1719: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
/home/pi/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexing.py:1719: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

**Comment by xmatthias** [comment]
It's warnings.

I'm yet to see a case where these actually create an issue. 
You can usually get around these by using `dataframe.loc[:, 'newcol'] = ...` ... however there's no guarantee this will completely fix the issue, as even then, the warning can appear as part of a false positive.
