### ISSUE TITLE
'No module named 'technical'' when tried to use MultiRSI.py

### ISSUE THREAD

**Issue by me6ran** [freqtrade/freqtrade-strategies#131]
looks like freqtrade does not have "technical" module/folder, so when tried to use: freqtrade-strategies/user_data/strategies/berlinguyinca/MultiRSI.py, it returns error:
 due to 'No module named 'technical''

**Comment by xmatthias** [comment]
technical is a seperate [module](https://github.com/freqtrade/technical), which needs to be installed with `pip install technical` - or with `pip install git+https://github.com/freqtrade/technical`.
