### ISSUE TITLE
Hyperopt and backtesting not matching

### ISSUE THREAD

**Issue by GuuhBoss** [freqtrade/freqtrade-strategies#137]
So there are few days I have trying to figure out what's the problem and I cant find..

Maybe I pretty noob at python, I dont know..

but its a pretty simple strategy, based on RSI and MACD its described on the file also.

There are 2 things I would like to comment before you open.
1.  At Strategy I have commented, stoch rsi. because its for further improvement, where I wanna add informative pair based on 4h timeframe.

2. At Hyperopt I commented the strategy, because I wanna it to use the actual strategy to improve, and by what i read, its just do it if there is not a strategy.

Feel free to check it, and tell me something.  I have prints of the hyperopt and backtests, but I dont know if its needed share because its not doing good.

Thanks since now :)

Edit: I hope i posted on the right place, I dont know much about github either

[Strategy.zip](https://github.com/freqtrade/freqtrade-strategies/files/6193165/Strategy.zip)

**Comment by xmatthias** [comment]
on a quick glance i'd say your strategy and hyperopt has not much in common.

Whatever the output is - you should follow this and use THAT conditional for the output.
for example:

hyperopt: `conditions.append( dataframe['rsi'] < params['rsi-value'] )`
backtesting: `(dataframe['rsi'].shift(5) <= 44) &`

the correct would be `(dataframe['rsi'] <= 44) &` .

I guess the same can happen to many other lines as well.
In the end, matching hyperopt and backtesting is pretty easy if you keep an eye out on the details.
We do however not provide extended help on this - as it's usually only oversights that lead to this - which will cost us time which will much better be spent looking at real bugs and enhancements.
