### ISSUE TITLE
populateStopLoss

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade-strategies#142]
can you add an easy option like that to make stoploss optional?:
```

stoploss=populateStopLoss(order-info) or float

Def populateStopLoss(order-info):
   X x x x 
   return (different float number for any order)

```

**Comment by xmatthias** [comment]
Please read the [documentation](https://www.freqtrade.io/en/latest/configuration/#parameters-in-the-strategy) ​before posting issues which ask things  covered by the documentation.

Stoploss is technically optional in the strategy - but you must define it in either strategy or configuration.
Running strategies without any stoploss is not supported (and there are no plans in doing so) - as we require the user to either explicitly aknowledge the risk of running without stoploss (by defining a very large stoploss) - or using a stoploss that corresponds to the user's risk profile.

**Comment by mablue** [comment]
I know that.stoploss a constant value that will setted inside of strategy.
But sometimes we need to get more risk to get more profit !
Or small risk for getting minimum damage .
Its strongly connected with the information we get from the ohlcv
