### ISSUE TITLE
Can anyone help implementing the TV flawless 15min btc hyperopt?

### ISSUE THREAD

**Issue by salehhashemi1992** [freqtrade/freqtrade-strategies#143]
I think it will be very good if someone implement this strategy and hyperopt specially the v2:
https://www.tradingview.com/script/i3Uc79fF-Flawless-Victory-Strategy-15min-BTC-Machine-Learning-Strategy/

What indicators are required?
RSI and bollinger band for v2 of the  @strategy

the Buy Strategy:
Completely explained in the above link.

the Sell Strategy:
Completely explained in the above link.

Source:
https://www.tradingview.com/script/i3Uc79fF-Flawless-Victory-Strategy-15min-BTC-Machine-Learning-Strategy/

**Comment by snussik** [comment]
@salehhashemi1992 what's the problem to use rsi and bb indicators?
By the way, I think that the author used freqtrade before ported strategy to pine script. 

p.s. strategy's good enough on bull market, but sucks on bearish.
