### ISSUE TITLE
Prevent Hyperopt from minimising trades

### ISSUE THREAD

**Issue by snussik** [freqtrade/freqtrade-strategies#145]
I've noticed, that Hyperopt tries to minimise trades on the bullish market time ranges. Actually - it gives optimised parameters that make buy&hold strategy from any provided, if you set a full range of parameter values ( from 0 to 100).
On the bullish market it makes 1 trade for period with max profit.
I use `--spaces buy sell` and `DefaultHyperOptLoss` flags. 

Is it possible to prevent Hyperopt from this behaviour?

**Comment by xmatthias** [comment]
hyperopt has a parameter - `--min-trades <value>` - where you can specify what minimum trade amount youd want.
Obviously this parameter will need adjustment with different strategies / timeframes / timeranges / expectations - but if the hyperopt result is below that value, the loss-function is ignored and a very high value (signaling a very bad epoch) is asumed.
