### ISSUE TITLE
Cannot understand BinHAndCluc strategy

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade-strategies#146]
Hello, I would like to understand the strategy CombinedBinHAndCluc

specifically those lines, the rest is kinda clear:

                    dataframe['lower'].shift().gt(0) &
                    dataframe['bbdelta'].gt(dataframe['close'] * 0.008) &
                    dataframe['closedelta'].gt(dataframe['close'] * 0.0175) &
                    dataframe['tail'].lt(dataframe['bbdelta'] * 0.25) &
                    dataframe['close'].lt(dataframe['lower'].shift()) &
                    dataframe['close'].le(dataframe['close'].shift())

what is expressed in those lines? the rows of ClufMay72018 are clearer. 
                    (dataframe['close'] < dataframe['ema_slow']) &
                    (dataframe['close'] < 0.985 * dataframe['bb_lowerband']) &
                    (dataframe['volume'] < (dataframe['volume_mean_slow'].shift(1) * 20))

Here it says that if dataframe(close) is smaller than number.

What happens at the above area of BinHV45? There are no expressions like > or <.

Thanks in advance!

**Comment by xmatthias** [comment]
well `.lt()` == `<` and `.gt()` = `>`... so it's simply using a slightly different syntax than what most people are used to.
There's no benefit (nor drawback) to using this syntax - but it doesn't require wrapping parenteses - and i guess the author was more familiar with this approach than with the approach used in most other examples.


the numbers are ... to kinda get the values to align (be in the same ballpark).
For example, bbdelta will be the difference between upper and lower band IIRC - so this must be greater than 0.8% of the pair's price (if current price is 100$ - move this value to 0.8$ for the comparison).

if these values are ... working for all pairs or not i'm not sure - but it seems they're kinda good as i know many people use either this or BinHV45.
