### ISSUE TITLE
ReinforcedSmoothScalp not working

### ISSUE THREAD

**Issue by Facepipe** [freqtrade/freqtrade-strategies#147]
Hi,
I connot get ReinforcedSmoothScalp to load.

Ubuntu 20 .04

![image](https://user-images.githubusercontent.com/81903837/113504446-0af92100-9530-11eb-93c0-ec4ea02d87d5.png)
![image](https://user-images.githubusercontent.com/81903837/113504459-1c422d80-9530-11eb-906f-0748140aa83b.png)

**Comment by xmatthias** [comment]
The message in your logs is pretty clear. 

You miss the technical module - which can be installed by running `pip install technical`.

For the future: please get used to pasting logs as text, not as screenshots, that will avoid having to open a picture just to read text, thanks.

**Comment by Facepipe** [comment]
Thank you and sorry for the screenshots
I have followed the install instructions on freqtrade.io

(.env) helm@HELM:~/freqtrade$ sudo python3 -m pip install "technical"
Requirement already satisfied: technical in /usr/local/lib/python3.8/dist-packages (1.2.2)
Requirement already satisfied: TA-Lib in /usr/local/lib/python3.8/dist-packages (from technical) (0.4.19)
Requirement already satisfied: pandas in /usr/lib/python3/dist-packages (from technical) (0.25.3)
Requirement already satisfied: arrow in /usr/local/lib/python3.8/dist-packages (from technical) (1.0.3)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from TA-Lib->technical) (1.17.4)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/lib/python3/dist-packages (from arrow->technical) (2.7.3)

**Comment by xmatthias** [comment]
as said - the logs indicate that you don't.

you're also using sudo - based on your log output, this will NOT use your virtual environment, so technical is installed in the system python ... but not in the virtual environment - and therefore it's not available for freqtrade.
