### ISSUE TITLE
Usage of short operations in pair trading.

### ISSUE THREAD

**Issue by SoupBoris** [freqtrade/freqtrade-strategies#151]
## Step 1: What indicators are required?
Bollingerbands
Informative pairs

## Step 2: Explain the Buy Strategy
Bollingerbands necessary to measure divergence
Informative pair to know that the other pair is doing crazy things as well but in the other direction.
When two coins divert which we assume are closely correlated divert from each other by a certain bollinger band measure, **long buy** the one that fell and **short buy** the one that increased in price.

## Step 1: Explain the Sell Strategy
Bollinger bands necessary to measure going back to normal.
Once either of the assets go back to a closer to mean or the middle bollinger band produce a sell signal on that asset.

## Source
Market neutral pair trading
* https://www.investopedia.com/articles/trading/04/090804.asp
My question is, how (if it even is possible) do I implement a shorting position using freqtrade?

It would be game changing.

**Comment by xmatthias** [comment]
Entering short positions is currently not possible with freqtrade.

Best subscribe to the original issue for updates on this (https://github.com/freqtrade/freqtrade/issues/892) - but also don't expect anything anytime soon, as this will first require margin support (https://github.com/freqtrade/freqtrade/issues/2312) - which is not yet fully unified in Ccxt as far as i know.

**Comment by Jay54520** [comment]
@xmatthias Do you know another bot in github which support shorting?

**Comment by samgermain** [comment]
@Jay54520 

Working on it, #5157

If you would like to contribute to the implementation, message me on discord samwow#2769
