### ISSUE TITLE
Help with Stochastic + RSI + MACD Trading Strategy need

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade-strategies#152]
Hi, this is my first try at python programming. please tell me my faults so they can be improved :)

## Step 1: What indicators are required?
fastk, fastd, macdsignal, macd, rsi

## Step 2: Explain the Buy Strategy
fastk & fastd reach oversold (<20)
check rsi crossing > 50
check macdsignal crossing > macd

## Step 1: Explain the Sell Strategy
fastk & fastd reach overbought (>80)
check rsi crossing < 50
check macdsignal crossing < macd

## Source
What come from this strategy? Cite your source:
https://www.youtube.com/watch?v=hh3BKTFE1dc

the code errors at the line 
if stoch['fastk'].shift(x) > 80:
**could you tell me why? thanks in advance!**
**also: please tell me how I could debug this with visual studio (or at least nudge me in the right way :) )**

This is by no means complete, couldnt even get it to run in the first place :x
`# --- Do not remove these libs ---
from freqtrade.strategy.interface import IStrategy
from pandas import DataFrame
# --------------------------------

class RsiMacdStochStrategy(IStrategy):
    # Minimal ROI designed for the strategy.
    # adjust based on market conditions. We would recommend to keep it low for quick turn arounds
    # This attribute will be overridden if the config file contains "minimal_roi"
    #minimal_roi = {
    #    "0": 0.01
    #}

    # Optimal stoploss designed for the strategy
    #stoploss = -0.25

    # Optimal timeframe for the strategy
    #timeframe = '5m'

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        stoch = ta.STOCHF(dataframe)
        dataframe['fastd'] = stoch['fastd']
        dataframe['fastk'] = stoch['fastk']
        dataframe['fastd_underbought_before'] = 0
        dataframe['fastk_underbought_before'] = 0
        dataframe['fastd_overbought_before'] = 0
        dataframe['fastk_overbought_before'] = 0
        dataframe['fastd_rising_since'] = 0
        dataframe['fastk_rising_since'] = 0

        dataframe['rsi'] = ta.RSI(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        
        for x in range(1,50):
            if stoch['fastd'].shift(x) > 80:
                break
            if stoch['fastd'].shift(x) < 20:
                dataframe['fastd_underbought_before'] = x
                break
        
        for x in range(1,50):
            if stoch['fastk'].shift(x) > 80:
                break
            if stoch['fastk'].shift(x) < 20:
                dataframe['fastk_underbought_before'] = x
                break
        
        for x in range(1,dataframe['fastd_underbought_before']):
            if stoch['fastd'].shift(x) > 80:
                dataframe['fastd_overbought_before'] = x
                break

        for x in range(1,dataframe['fastk_underbought_before']):
            if stoch['fastk'].shift(x) > 80:
                dataframe['fastk_overbought_before'] = x
                break
        
        for x in range(1,10):
            if dataframe['fastd'].shift(x) < dataframe['fastd_rising_before']:
                break
            if dataframe['fastd'].shift(x) >= dataframe['fastd_rising_since']:
                dataframe['fastd_rising_since'] = x
                
        for x in range(1,10):
            if dataframe['fastk'].shift(x) < dataframe['fastk_rising_before']:
                break
            if dataframe['fastk'].shift(x) >= dataframe['fastk_rising_since']:
                dataframe['fastk_rising_since'] = x
                
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                dataframe['fastd_rising_since'] > 0 & 
                dataframe['fastk_rising_since'] > 0 &
                dataframe['fastd_underbought_since'] > 0 &
                dataframe['fastk_underbought_since'] > 0 &
                dataframe['rsi'] > 50 &
                dataframe['macd'] > dataframe['macdsignal'] &
                dataframe['fastd'] < 80 &
                dataframe['fastk'] < 80 &
                dataframe['fastd_underbought_before'] >  dataframe['fastd_overbought_before'] &
                dataframe['fastk_underbought_before'] >  dataframe['fastk_overbought_before'] &
            ),
            'buy'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                dataframe['fastd_overbought_before'] > 0 &
                dataframe['fastk_overbought_before'] > 0 &
                dataframe['rsi'] < 50 &
                dataframe['macd'] < dataframe['macdsignal'] &
                dataframe['fastd'] > 20 &
                dataframe['fastk'] > 20
                ),
            'sell'] = 1
        return dataframe
`

**Comment by xmatthias** [comment]
You cannot use `if` to compare dataframes.
A dataframe is similar to a table, containing multiple rows.
your if statements will therefore fail as it'll compare multiple rows, not just one row.

You should get familiar with how pandas work, as it will require a slightly different approach to think about things like this - as each condition you apply should ideally apply to the whole dataframe at once - not just one row.

We do however not provide basic pandas support, best use google for this, as there are many good tutorials around.

**Comment by hippocritical** [comment]
thanks
