### ISSUE TITLE
SuperTrend strategy from tradingview.

### ISSUE THREAD

**Issue by leonardvdj** [freqtrade/freqtrade-strategies#156]
*For requestion a new strategy. Please use the template below.*  
*Any strategy request that does not follow the template will be closed.*

## Step 1: What indicators are required?
HL2
ATR

## Step 2: Explain the Buy Strategy
When the price is over the trend, buy

## Step 1: Explain the Sell Strategy
When the price is under the trend, sell

## Source
What come from this strategy? Cite your source:
* https://github.com/exit490/tradingview-strategies-and-indicators/blob/master/supertrend_atr_with_tsl/supertrend-whit-tsl-strategy.pine

The main thing I need help with is the section starting at line 125.
```
atr = 3 * ta.ATR(dataframe, timeperiod=10)
hl2 = (dataframe["high"] + dataframe["low"]) / 2

dataframe["longStop"] = hl2 - atr
longStopPrev = dataframe["longStop"].shift(1) or dataframe["longStop"]
dataframe["longStop"] = max(dataframe["longStop"], longStopPrev) if dataframe["close"].shift(1) > longStopPrev else dataframe["longStop"]

dataframe["shortStop"] = hl2 + atr
shortStopPrev = dataframe["shortStop"].shift(1) or dataframe["shortStop"]
dataframe["shortStop"] = min(dataframe["shortStop"], shortStopPrev) if dataframe["close"].shift(1) < shortStopPrev else dataframe["shortStop"]

dataframe["direction"] = 1
directionPrev = dataframe["direction"].shift(1) or dataframe["direction"]
dataframe["direction"] = 1 if directionPrev == 1 & dataframe["close"] > shortStopPrev else -1 if directionPrev == 1 and dataframe["close"] < longStopPrev else directionPrev
```

This is my crack at it, however the problem I'm having is pandas complains about "the truth value of a series is ambiguous", and I've sat for a couple hours now trying to fix it but I simply cannot figure out what it is that needs to be changed.
Any help would be greatly appreciated.
I know there's already an issue with another supertrend, however that one doesn't seem to give me similar results to this one, hence wanting to convert this one.

**Comment by xmatthias** [comment]
You clearly can't use ` dataframe["longStop"].shift(1) or dataframe["longStop"]` - as that's not really vectorized.

you should instead be able to use `np.where(dataframe["longStop"].shift(1), dataframe["longStop"].shift(1), dataframe["longStop"])` (or explicitly checking the first argument for `.isna()`  ... 

obviously, the same will apply to basically all your `if` / `or` statements ...
