### ISSUE TITLE
Hyperopt - MemoryError: Unable to allocate 1.78 MiB for an array with shape (233898,) and data type float64

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade-strategies#158]
Hi Mattias, I was hyperopting my strategy today and got this error: 

- MemoryError: Unable to allocate 1.78 MiB for an array with shape (233898,) and data type float64

This occured after the 37th epoch. It generally happens when I hyperopt many values (even if I select to hyperopt just one space of the strategy at a time). Is this something I can avoid with a better hardware?

In particular, if that's the case, what should I look for? (example: more RAM, more x, more y, etc..). Thanks for you answers!

**Comment by xmatthias** [comment]
as it's a memory error, it'll be Ram for sure.

now depending on when (at what point in the process) the error is received, you've either got very low RAM - or too many pairs / too long timerange.
You can also limit parallelism (`-j x`) - as every process get's the full dataframe in memory once.

**Comment by Fimap9to1** [comment]
I've done it with a 8gb ram so that's probably the issue. I'll try with a different hardware, thanks!

Pairs are roughly 200

**Comment by Fimap9to1** [comment]
What about parallelism, is that something I can input in the command ? Where has it to be placed?

**Comment by xmatthias** [comment]
you can limit the number of cores used with `-j` - as mentioned above (and in the docs).

**Comment by Fimap9to1** [comment]
Great thanks!
