### ISSUE TITLE
Hedging strategy

### ISSUE THREAD

**Issue by EloutV** [freqtrade/freqtrade-strategies#162]
## Step 1: What indicators are required?

No specific request regarding indicators

## Step 2: Explain the Buy Strategy

Is it possible to have a strategy that starts with sell followed by buy, instead of the other way around.
In order to protect my BTC account when BTC drops heavily I would like to ha e the opportunity to buy EUR or USDT as a hedge (sell BTC when it starts dropping, buy BTC back when it starts picking up again).
But, EURBTC or USDTBTC are not available currency pairs, but BTCEUR and BTCUSDT are. So, if I set up this strategy in EUR as base currency, I could like my strategy start a trade with selling to BTC and buy back later. 
Is there a way to do this? 
 

## Step 1: Explain the Sell Strategy

See buy strategy

## Source
What come from this strategy? Cite your source:
* http://

**Comment by xmatthias** [comment]
Currently, there is no way to short-sell with freqtrade. All trades follow the logic of "buy first, then hold, then sell".

On certain exchanges, you may get around this by using *DOWN/* pairs (which usually roughly follow the reverse movements of their counterparts) - but they are often leveraged, so have a higher risk profile.

You can subscribe to https://github.com/freqtrade/freqtrade/issues/892 or https://github.com/freqtrade/freqtrade/issues/2312 to track progress on this - but don't expect any very soon as this is currently not very high on the agenda.

**Comment by EloutV** [comment]
Thnx for the explanation.

**Comment by samgermain** [comment]
@Jay54520

[Working on it](https://github.com/freqtrade/freqtrade/pull/5157)

If you would like to contribute to the implementation, message me on discord samwow#2769
