### ISSUE TITLE
How can I control Stoploss dynamicly with timeframe?

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade-strategies#165]
How can I make an strategy that have a dynamic staploss?
For example if 
timeframe = 1h

Stoploss at 0 ~ 1 hour after buy = -10%
Stoploss at 1 ~ ∞ hour after buy = -2%

I need it cuz my strategys is working good in backtest.cuz of missed data of smaller timeframes candles.but in real after one minute with -2% loss the bot reaches to stoploss.
I need to ignore stoploss for one hour after buy in one hour timeframes.and ignore 2hours in 2hour timeframe.
I fix it with setting stoploss to 1 and hyperopt without stoploss and again hyperopt it with just stoploss than just can get bigger stoplosses(-10%)
But its not prementelly fixes the problem.

**Comment by xmatthias** [comment]
You can use [custom stoploss](https://www.freqtrade.io/en/stable/strategy-advanced/#custom-stoploss) for that.

Stoploss itself does not support timebased dynamics - although you could use trailing (with trailing offset) to reach something similar - however the stoploss would in that case not be -2% after 1 hour, but -2% after it reaches a certain level of profit (which is most likely not what you're after).

**Comment by mablue** [comment]
I dont know what is what I want!
Just I can see it. I have an strategy with huge profitablity rate (0.1btc to fking 26btc in a month!!!)
And it just reaches to this profitablity just when the stoploss reaches to -0.02 in hyperopts!
Please help i need this mony :))

**Comment by snussik** [comment]
> Just I can see it. I have an strategy with huge profitablity rate (0.1btc to fking 26btc in a month!!!)

we are waiting for you in our billionaire's club )))

**Comment by mablue** [comment]
> > Just I can see it. I have an strategy with huge profitablity rate (0.1btc to fking 26btc in a month!!!)
> 
> we are waiting for you in our billionaire's club )))

It is just a backtest but Its very profitable strategy...
I get real 2x profit on some strategies!

**Comment by snussik** [comment]
Maybe its so. But I even didn't manage to run you strategy with default opt. It didn't make trades at all for me.

**Comment by mablue** [comment]
> Maybe its so. But I even didn't manage to run you strategy with default opt. It didn't make trades at all for me.

Change default values like dnaSize and configuration file.maybe you didnt hyperopt.hyperopt before use an strategy.and than copy the results on strategy.you have a problem on steps of running strategy I think.
