### ISSUE TITLE
Startup candle count for binance?

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade-strategies#166]
Hello, I can't find what the max startup_candle_count value is for binance can you point me to the right page please?

**Comment by xmatthias** [comment]
startup candle count is not relevant for trade modes, but only for backtesting/hyperopt.

For binance, it'll be 1000 (iirc) - but you should try to stay slightly below that - so assume 950 or so.

**Comment by Fimap9to1** [comment]
Ok thanks a lot!

**Comment by xmatthias** [comment]
it depends on the exchange - in general you can assume it's 500 (1000ish for binance) - however always assuming that the pair has sufficient age.

**Comment by Fimap9to1** [comment]
Ok great, thank for the information!
