### ISSUE TITLE
repeat hyperopts

### ISSUE THREAD

**Issue by nodwan** [freqtrade/freqtrade-strategies#170]
I have a small question. How often and in what rhythm do you repeat the hyperoptic? which period do you choose? e.g. 10 days or more or less? many thanks for your response.

**Comment by xmatthias** [comment]
well i'd say it depends ... (and you'll probably only get quite opinionated answers to this)...

Personally, i try to optimize a strategy to a wider range of data (including down / side / up-trends) - so i tend to not "re-hyperopt" very often.
Others may optimize to the last week - so you'll have to optimize more often ... it really depends on your strategy (and the goals of your strategy)
