### ISSUE TITLE
backtesting shows a profit of 1177.45%. Is this possible?

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade-strategies#172]
So I backtested [this strategy](https://github.com/aristosv/freqtrade/blob/main/strategies/Freqtrade_backtest_validation_freqtrade1.py), using [this configuration](https://github.com/aristosv/freqtrade/blob/main/configurations/config.json), and got [these results](https://github.com/aristosv/freqtrade/blob/main/backtesting/berlinguyinca/Freqtrade_backtest_validation_freqtrade1). 

Is it realistic, to expect this strategy to produce a profit of 1177.45%? We're talking about a 3 month period, with a maximum of 25 parallel trades, 1K portfolio, and a stake amount of $50.

My guess is that I messed something up somewhere and simply got back bloated results. I need to find what I did wrong so I can get a more realistic backtesting result.

**Comment by xmatthias** [comment]
This will probably not reproduce in dry-runs ...

You are using a very tight stoploss (1% on 1h candles) - which exploints one of the [backtesting assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting) - that price reaches high - and in case of a trailing stop - it'll sell 1% below this high.

For 1h candles, you'll have a 1h "blind spot" - where you don't know how the pair used.
Your trailing stop setting should therefore be bigger than what your pairs move on average during 1 hour.

Your signal is also "sticking" (it's always active when one line is above the other) - so you'll probably be in `max_open_trades`  95% of the time.

**Comment by aristosv** [comment]
> You are using a very tight stoploss (1% on 1h candles) - which exploints one of the [backtesting assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting) - that price reaches high - and in case of a trailing stop - it'll sell 1% below this high.
> 
> For 1h candles, you'll have a 1h "blind spot" - where you don't know how the pair used.
> Your trailing stop setting should therefore be bigger than what your pairs move on average during 1 hour.

I'm assuming this issue will be resolved if I decrease the timeframe to 5m? (instead of changing the stoploss)



> Your signal is also "sticking" (it's always active when one line is above the other) - so you'll probably be in `max_open_trades` 95% of the time.

What can I do to mitigate this issue?

**Comment by xmatthias** [comment]
1% is still pretty tight - but it'll be better than at 1h candles for sure.

You can use `crossed()` methods (look at the docs on usage) to detect the cross - instead of checking "whenever" one is above the other
That will create one signal - not a signal for X candles (which will then invert to a sell signal after the condition changes).

**Comment by aristosv** [comment]
great, thanks
