### ISSUE TITLE
python issue

### ISSUE THREAD

**Issue by BeastlyPixels** [freqtrade/freqtrade-strategies#174]
*For requestion a new strategy. Please use the template below.*  
*Any strategy request that does not follow the template will be closed.*

## Step 1: What indicators are required?
*Please list all the indicators required for the buy and sell strategy.*
dataframe['atr'] = ta.ATR(dataframe)
        dataframe['stoploss_rate'] = dataframe['close']-(dataframe['atr']*2)
        self.custom_info[metadata['pair']] = dataframe[['date', 'stoploss_rate']].copy().set_index('date')## 
Step 2: Explain the Buy Strategy
*Please explain in details the indicators you need to run the buy strategy, then
explain in detail what is the trigger to buy.*
buys when SAR is smaller then candle before  Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame
        :return: DataFrame with buy column## Step 1: Explain the Sell Strategy
*Please explain in details the indicators you need to run the sell strategy, then
explain in detail what is the trigger to sell.*
Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame
        :return: DataFrame with buy column## Source
What come from this strategy? Cite your source:
* http://

Getting the below error when trying to dry run, possibly from a change in syntax in python? Or potentially because I am using a different timezone than UTC on my bot? This is using the fixedriskreward strategy @JoeSchr , any help would be appreciated. Thank you!

freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error datetime.datetime(2021, 5, 5, 14, 14, 8, 828560, tzinfo=datetime.timezone.utc) calling <bound method FixedRiskRewardLoss.custom_stoploss of <FixedRiskRewardLoss.FixedRiskRewardLoss object at 0x7f4fc4745dc0>>
Traceback (most recent call last):
  File "/home/freq/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py", line 686, in get_loc
    return Index.get_loc(self, key, method, tolerance)
  File "/home/freq/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3092, in get_loc
    raise KeyError(key)
KeyError: Timestamp('2021-05-05 14:14:08.828560+0000', tz='UTC')

**Comment by BeastlyPixels** [comment]
That is odd, I downloaded the latest data before running it multiple times. Also, why not use it standalone? Backtesting seems to do well.

**Comment by xmatthias** [comment]
i don't think timezones will have an impact.

It's however pretty unclear from the issue above what you're trying to do.
Does this happen in backtesting - or as part of running this in dry/live modes?

**Comment by BeastlyPixels** [comment]
This happens on trying to do a dry run, backtesting works fine.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
