### ISSUE TITLE
bollinger bb_lowerband off compared to tradingview

### ISSUE THREAD

**Issue by mboogert** [freqtrade/freqtrade-strategies#183]
Hi all,

I'm trying to use the following indicator setup in my strategy:

```
bollinger = qtpylib.bollinger_bands(dataframe['close'], window=20, stds=2)
dataframe['bb_lowerband'] = bollinger['lower']
dataframe['bb_upperband'] = bollinger['upper']
dataframe['bb_middleband'] = bollinger['mid']
```

Somehow the lower and upper bands are completely off compared to the exact same setup on my tradingview chart.
This issue is causing false buy signals.

My buy signal is configured like this:

```
# Previous candle should cross the lower Bollinger Band
(dataframe['open'].shift(1) > dataframe['bb_lowerband'].shift(1)) &
(dataframe['close'].shift(1) < dataframe['bb_lowerband'].shift(1)) &

(dataframe['close'] > dataframe['bb_lowerband']) &
(dataframe['open'] < dataframe['bb_lowerband'])
```

## tradingview plot
![afbeelding](https://user-images.githubusercontent.com/11064438/119237287-52695a00-bb3c-11eb-9bb9-0b3fde2f23f6.png)
_The crosshair matches the buy signal of freqtrade as shown in the image below_

## freqtrade plot
![afbeelding](https://user-images.githubusercontent.com/11064438/119237303-6e6cfb80-bb3c-11eb-9404-fc46660606b5.png)

Does anyone have an idea what I'm doing wrong?

Thanx,
Marcel.

**Comment by xmatthias** [comment]
Depending on your pairs - i suspect you might be running into a pandas bug (#4382 - happening on BTC pairs).

It's expected to be fixed with the next (major) pandas version ... alternatively, look for any of the solution in the linked issue (most likely, `ta.BBANDS` is the most reliable one).

**Comment by mboogert** [comment]
Check! Thanx for your reply @xmatthias
