### ISSUE TITLE
Help question implement rNN & Arima

### ISSUE THREAD

**Issue by Cazs03** [freqtrade/freqtrade-strategies#187]
_In relation to the following strategy:_ 
[Using rNN and ARIMA to predict pairs price](https://www.kaggle.com/zikazika/using-rnn-and-arima-to-predict-bitcoin-price
)

Would it be possible to implement in freqtrade?
It seems that what is accumulating is the data to predict its future value.
Do you think it would be possible to do an implementation?

**Comment by xmatthias** [comment]
Everything you can code is possible.

Especially with ML, you'll need to be very careful of not introducing lookahead-bias - the details of which will often only appear once you start to analyze HOW the machine learning algorithm actually works.

So assuming you have a rather good / deep understanding of machine learning (and have implemented multiple models in the past) - then sure - it will be possible.

If you've never used these - then i would suggest to not start with it but start with a regular strategy.
