### ISSUE TITLE
Question about Zeus strategy

### ISSUE THREAD

**Issue by jpmolinamatute** [freqtrade/freqtrade-strategies#190]
This is a general question
I'm playing around with freqtrade backtesting and dry runs and multiple strategies from this repo.

I'm using Binance as exchange and freqtrade develop-e17e35f0

I first ran backtesting the Zeus strategy and I got a "kind of expected" result (a 90.05% profit yay!!!) but when I ran the dry trade I'm getting these warnings:

```
freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ETH/USDT: Dataframe returned from strategy has mismatching length.
freqtrade.strategy.interface - WARNING - Outdated history for pair ETH/USDT. Last tick is 27 minutes old
```

the last stick warning went from 27 min  to 45 min and then I just kept getting

```
freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ETH/USDT: Dataframe returned from strategy has mismatching length.
```

my question is what's happening here? I would like to understand what these warnings mean

thanks for the help, I appreciate it :-)

**Comment by shocker1185** [comment]
I have the same problem

**Comment by tamdinh** [comment]
I have the same question !

**Comment by xmatthias** [comment]
@mablue mind having a look at this?

**Comment by mablue** [comment]
ta library (not talib ) had this like problems befoure #189
there is no line of code on Zeus.py to fix it
also I use it now on dry and also you can see its warning.and strategy will work like charm;)

**Comment by ajithkirubakaran** [comment]
https://github.com/freqtrade/freqtrade-strategies/blob/d299b18666362e7f7dd9dbb718db54d94d6aa72b/user_data/strategies/Zeus.py 

[Result A] minimal_roi = { "0": 0.336, "134": 0.113, "759": 0.027, "1049": 0 } 

https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/Zeus.py 

[Result B] minimal_roi = { "0": 0.564, "567": 0.273, "2814": 0.12, "7675": 0 } 

Q1) I am a beginner to hyperoptimization. I came across these two files and I would like to learn what candle timeframes were used and what epoch parameter was used for hyperoptimization in [B] 

Q2) Is it optimum to run the hyperoptimization parameters alike [Result B] in Google Colab 12GB RAM version 

Kindly help. THANKYOU

**Comment by mablue** [comment]
> https://github.com/freqtrade/freqtrade-strategies/blob/d299b18666362e7f7dd9dbb718db54d94d6aa72b/user_data/strategies/Zeus.py
> 
> [Result A] minimal_roi = { "0": 0.336, "134": 0.113, "759": 0.027, "1049": 0 }
> 
> https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/Zeus.py
> 
> [Result B] minimal_roi = { "0": 0.564, "567": 0.273, "2814": 0.12, "7675": 0 }
> 
> Q1) I am a beginner to hyperoptimization. I came across these two files and I would like to learn what candle timeframes were used and what epoch parameter was used for hyperoptimization in [B]
> 
> Q2) Is it optimum to run the hyperoptimization parameters alike [Result B] in Google Colab 12GB RAM version
> 
> Kindly help. THANKYOU
each setting in your config will not be change after hyperoptimzation all tfs work good ;)
i cant undrestand you İ didnt used google co lab!?!?

**Comment by ajithkirubakaran** [comment]
The roi table i generated for -e 500 gave drastic profit percentage changes while backtesting different timeframes. But the one you generated performed fair enough while backtesting different timeframes. I use Google colab for running hyperoptimization. Will it be able to handle more epoch for hyperoptimizing alike you. Kindly help with hyperoptimization for better performance. THANKYOU

**Comment by mablue** [comment]
set a manual roi and stoploss and run the hyperopt with this command
-spaces buy sell

**Comment by ajithkirubakaran** [comment]
I did backtest only after changing the config according to hyperopt results

**Comment by arunvibe** [comment]
Yeah I have also ran hyperoptimization for -e 500 but after changing config according to hyperopt results I did the backtest process which didn't yield satisfying results for different timeframes AS YOUR ROI({ "0": 0.564, "567": 0.273, "2814": 0.12, "7675": 0 })
why? there is a   difference

**Comment by mablue** [comment]
you two @ajithkirubakaran and @arunvibe are fucked my mind.
just update to end merged version and do a hyperopt and fun thats it

**Comment by maestro73** [comment]
@ajithkirubakaran I'd like to know how did you do to run Hyperopt on Google Colab.
Thanks

**Comment by mablue** [comment]
![Screenshot_20210824-213228](https://user-images.githubusercontent.com/5004900/130659083-adbdb980-056f-465d-9ad3-b6848cd7fcbf.png)

**Comment by mablue** [comment]
![Screenshot_20210824-213648](https://user-images.githubusercontent.com/5004900/130659635-8888405c-2693-443b-8899-50e507166065.png)

**Comment by maestro73** [comment]
thanks!!!

**Comment by ajithkirubakaran** [comment]
@maestro73 
https://colab.research.google.com/drive/1JfuwDN1bnhugbJldbUF3FDnqUBpl_nhL?usp=sharing

**Comment by mablue** [comment]
> @maestro73
> https://colab.research.google.com/drive/1JfuwDN1bnhugbJldbUF3FDnqUBpl_nhL?usp=sharing
hard !
![Screenshot_20210824-213648](https://user-images.githubusercontent.com/5004900/130659635-8888405c-2693-443b-8899-50e507166065.png)
gpu optimize disabled...
