### ISSUE TITLE
Unable to analyze candle when using Zeus strategy

### ISSUE THREAD

**Issue by aczire** [freqtrade/freqtrade-strategies#191]
The below error is thrown frequently when using Zeus strategy. Could this be because the trade is running on `DryRun` mode  and is not able to lookback past a set limit? 

> freqtrade    | 2021-05-31 05:54:28,620 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ALGO/BTC: Dataframe returned from strategy has mismatching length.
> freqtrade    | 2021-05-31 05:54:28,648 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ATOM/BTC: Dataframe returned from strategy has mismatching length.
> freqtrade    | 2021-05-31 05:54:28,675 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BAT/BTC: Dataframe returned from strategy has mismatching length.
> freqtrade    | 2021-05-31 05:54:28,703 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BCH/BTC: Dataframe returned from strategy has mismatching length.
> freqtrade    | 2021-05-31 05:54:28,730 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BRD/BTC: Dataframe returned from strategy has mismatching length.
> freqtrade    | 2021-05-31 05:54:28,764 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair EOS/BTC: Dataframe returned from strategy has mismatching length.
> freqtrade    | 2021-05-31 05:54:28,825 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair IOTA/BTC: Dataframe returned from strategy has mismatching length.
> freqtrade    | 2021-05-31 05:54:28,915 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair NEO/BTC: Dataframe returned from strategy has mismatching length.
> freqtrade    | 2021-05-31 05:54:28,940 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair XMR/BTC: Dataframe returned from strategy has mismatching length.
> freqtrade    | 2021-05-31 05:54:28,997 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair XTZ/BTC: Dataframe returned from strategy has mismatching length.
> freqtrade    | 2021-05-31 05:54:29,037 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair TRU/BTC: Dataframe returned from strategy has mismatching length.

**Comment by xmatthias** [comment]
Please use the search before opening a new issue. This has been opened just yesterday in 
#190.

**Comment by abhi1010** [comment]
I am seeing the same error on `GodStra.py` file. 

```
freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ATM/USDT: Dataframe returned from strategy has mismatching length.
```
Does this mean the same solution needs to be applied to that strategy as well?
