### ISSUE TITLE
Tried to run hyperopt on GodStraHo and it gave an ta module not found

### ISSUE THREAD

**Issue by videogamingeducation** [freqtrade/freqtrade-strategies#192]
I tried to run the GodStraHo hyperopt using docker and it said that GodStra.py cannot be imported due to missing ta module. I understand that you should install requirements for manual installation but what about for docker? I thought that hyperopt dependencies are already included?

**Comment by xmatthias** [comment]
ta is not a hyperopt dependency, but a dependency specific to this strategy.

As such - you'll need to extend the docker image and install the necessary modules based on [the documentation](https://www.freqtrade.io/en/latest/docker_quickstart/#additional-dependencies-with-docker-compose).
