### ISSUE TITLE
Difference Hyperopt Backtest - ReinforcedSmoothScalp

### ISSUE THREAD

**Issue by JipVerbiest** [freqtrade/freqtrade-strategies#193]
Hello all,
I am having an issue getting the same results from backtesting as I do form the hyperoptfunction for ReinforcedSmoothScalp.

Period and parameters are the same and I think I did not miss the any of the parameters.
Where is the issue happening?

I included my hyperopt and strategy + terminal logs.

Thanks for the help. I hope someone can help solve this issue. 

[ReinforcedSmoothScalp_hyperopt.txt](https://github.com/freqtrade/freqtrade-strategies/files/6594591/ReinforcedSmoothScalp_hyperopt.txt)
[ReinforcedSmoothScalp.txt](https://github.com/freqtrade/freqtrade-strategies/files/6594592/ReinforcedSmoothScalp.txt)

[Backtest terminal.txt](https://github.com/freqtrade/freqtrade-strategies/files/6594600/Backtest.terminal.txt)
[Hyperopt terminal.txt](https://github.com/freqtrade/freqtrade-strategies/files/6594601/Hyperopt.terminal.txt)

**Comment by xmatthias** [comment]
your`buy_strategy_generator` and the `populate_buy_trend` in the strategy have "rather different" approaches and conditions.
While the strategy will use open < ema_low - there's no notion about this condition in `buy_strategy_generator` (it's probably the same with other conditions - but i'll leave this discover work up to you.

**Comment by JipVerbiest** [comment]
Hi Matthias,
Thanks for your answer. I have been looking an tweaking in the hyperopt but still don't manage to align it perfectly with the backtest.

Concerning the conditions. The only variable values in the backtest are fastd, fastk, adx and mfi, which the hyperopt returns (and whether they have to be enabled or not).

I don't think the ema_high and ema_low have to be included in the hyperopt as their timeframe is fixed on 5 in the strategy. As this is fixed, why would the hyperopt show a different result if it only can play with fastd, fastk, adx and mfi? 

The populate_buy_trend and the populate_sell_trend are identical copies between the strategy and hyperopt.
What do I have to add to the hyperopt to align the results? I do not see what is missing. Is it the ema with a variable time period?

Thanks for your help already

**Comment by xmatthias** [comment]
you'll need to be careful - when you hyperopt, it's not the instance function (the one with self, at the bottom) that counts, but the one nested in the `buy_strategy_generator` function.

It's slightly missleading, so maybe removing the bottom 2 functions will be beneficial (i did that now in the repository).

**Comment by JipVerbiest** [comment]
Hi Matthias,

Thank you for this tip. I was indeed confused by the bottom functions. 
I have edited the strategy from hard coded values to variables, and declared and named the values the same in the hyperopt file.

After having ran tens of times through the hyperopt page in the documentation, I think I must be right. The results from backtest still deviate from the hyperopt though. I only worked with guards and trends and not with triggers. I declared all of them I want hyperopt to optimize and implemented the categoricals in the strategy. 

Tried -dmmp and -eps as well, but the results still don't match.

There must still be a little mistake somewhere but I did not manage to find it.

Am I right on this?: Hyperopt runs the strategy as defined in the strategy file, and optimizes the parameters I added under buy strategy generator. The categorical checks whether the indicator has to be used or not at all. The parameters under buy strategy generator are the same ones as the variables declared in the strategy, so it is literally adjusting these each epoch in the strategy to find whether the epoch was more successful than the previous one.

Is there anything you see fundamentally wrong in my hyperopt file or thinking? Or did I miss something in the code?

Thank you for your help.
Jip
[Smoothscalp strategy+hyperopt.zip](https://github.com/freqtrade/freqtrade-strategies/files/6671885/Smoothscalp.strategy%2Bhyperopt.zip)

**Comment by xmatthias** [comment]
You'll have to take a pick - EITHER use inlined strategy parameters, OR use a hyperopt file.

combining both will not work and is not supported.
Also - consider the seperate hyperopt-file as the "legacy" mode - which is still supported, but not recommended for new Files.

**Comment by JipVerbiest** [comment]
Thanks Matthias!
Just not using the strategy only already solved the problem. Thanks for your help. Really appreciated!
