### ISSUE TITLE
DataProvider only available in populate_indicators()

### ISSUE THREAD

**Issue by nullprobe** [freqtrade/freqtrade-strategies#194]
The DataProvider class is referenced in populate_buy_trend() and according to the documentation (https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-dataprovider) it can only be used in populate_indicators()

Reference : https://github.com/freqtrade/freqtrade-strategies/blob/8e038352f528fdac7d02a32ba13505b5cd7bfdc2/user_data/strategies/DevilStra.py#L588

DevilStra.py errors out while running hyperopt, due to a 'NoneType' error since self.dp does not exist.

**Comment by xmatthias** [comment]
Nice catch.

@mablue - i think your strategies will need quite some work (considering this and #190) to work reliably ...

**Comment by mablue** [comment]
@xmatthias if It's make problem I can add move it to populate indicators  so  i just use result on populate buy and sell?

**Comment by xmatthias** [comment]
no it ain't a problem - the way it's designed works perfectly fine (i was kindof misled initially ...)

**Comment by nullprobe** [comment]
I'm afraid I don't understand the "split hyperopt and backtesting methods". I'm using the command specified in the DevilStra : 
`freqtrade hyperopt --hyperopt-loss SharpeHyperOptLoss --spaces buy sell -s 𝕯𝖊𝖛𝖎𝖑𝕾𝖙𝖗𝖆`

What would be the correct workflow to make this work?

**Comment by mablue** [comment]
> I'm afraid I don't understand the "split hyperopt and backtesting methods". I'm using the command specified in the DevilStra :
> `freqtrade hyperopt --hyperopt-loss SharpeHyperOptLoss --spaces buy sell -s 𝕯𝖊𝖛𝖎𝖑𝕾𝖙𝖗𝖆`
> 
> What would be the correct workflow to make this work?

backtesting just show the result in a time period
with settings inside an strategy but hyperopt show the new possable results with new all possable settings.
also you should read the freqytade documents to undrestand good.
you will change stylish 𝕯𝖊𝖛𝖎𝖑𝕾𝖙𝖗𝖆 to the exact file name (devilStra) to run your hyperopt.and at the end you should copy the result and paste in the exact place (overwrite)

**Comment by nullprobe** [comment]
I understand the difference between hyperopt and backtesting, and that stylish DevilStra was just copypasted from the file. I use normal ascii on the CLI.
The thing is, I'm getting a NoneType error running that command because of the DP. Am I not running it correctly?

**Comment by xmatthias** [comment]
the command looks ok - but availability of dataprovider in hyperopt will depend on your version - and was only added in the last 2 (or so) versions.

**Comment by nullprobe** [comment]
Got it! I checked out the develop branch to test it and it seems to work.
Thanks for the fast response!
