### ISSUE TITLE
Stock Prediction Models

### ISSUE THREAD

**Issue by a178235** [freqtrade/freqtrade-strategies#203]
I found this, https://awesomeopensource.com/project/huseinzol05/Stock-Prediction-Models, and the Evolution-Strategy Agent , #6, seems to perform well. Could this be implemented?

## Step 1: What indicators are required?

This used TensorFlow to determine buy and sell signals.

## Source

https://github.com/huseinzol05/Stock-Prediction-Models/blob/master/agent/6.evolution-strategy-agent.ipynb

**Comment by xmatthias** [comment]
Everything that needs <1m data will probably not work due to lack of data - nor will relying on orderbooks work (at least not for backtesting).
Exchanges don't provide this information for backtesting - nor do they really provide real-time information about it.

if it fits into the above constraints - you might be successfull in implementing things ... but if it doesn't - it's probably not going to work.

**Comment by snussik** [comment]
@xmatthias I've noticed that agent's approach is to make multiple buys in different market states. And if I correctly understand current bot functionality - it can make only one buy on one market on one symbol. And after that it only can hold or sell. 
So this type of pool learning won't work here. Am I right?

**Comment by xmatthias** [comment]
If that's how it works - then yes, it's currently not possible (although there's an old issue which tries to change this).

**Comment by a178235** [comment]
I have done testing with 1m candles using strategy #6. It will make multiple buys and sells, although I'm only interested in 1 per pair, i.e. the buy and sell signals. I'm just not that up on TensorFlow, but thought I'd mention it as after learning, it seems to perform well on test data.

**Comment by snussik** [comment]
@a178235 the link you gave doesn't use tensor flow. Just simple Numpy arrays. Buy the way, Ive tried to run the code from the link below with this condition: `if bought then sell or hold` on the given `GOOG-year.csv` data & have got the following result from 10000 initial balance: `day 248, sell 1 unit at price 1019.270020, investment 4.802791 %, total balance 10285.960023`
So it's not a Graal at all to have 4% apy on backtest.

**Comment by a178235** [comment]
Ah, yes, that one does not use TensorFlow, but scikit-learn, sorry. I used testing datesfrom 5/19- and 6/20- and 6/25-6/26 using 1 minute data and is doing well. I wanted to make sure it was working well on some downtrends also. I can do more tests and share the data and results if interested.

**Comment by snussik** [comment]
@a178235  there is no scikit there: https://github.com/snussik/evmodel.git  You are welcome to look yourself. The code with one buy/sell condition.

**Comment by a178235** [comment]
You are correct. I also found this, https://github.com/huseinzol05/Stock-Prediction-Models/tree/master/realtime-agent. Would that be something of interest?

**Comment by snussik** [comment]
@a178235 I think that the idea: let's take some ml algorithm and make model is not a strategy. 
You should think about 2 main questions:
1. What kind of data you feed to algorithm (as prices are definitely not enough).
2. What kind of model you should use. Ltsm, gan or simple regressions work different on same dataset.

The repository is just a set of examples.

**Comment by xmatthias** [comment]
Just a suggestion - maybe discussing this in the [discord server](https://discord.gg/p7nuUNVfP7) might be the better / faster way?

**Comment by a178235** [comment]
Thanks, will do.
