### ISSUE TITLE
ReinforcedSmoothScalp

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade-strategies#21]
try to use --strategy=ReinforcedSmoothScalp with last freqtrade source get the error
 File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle staticmethod objects

**Comment by xmatthias** [comment]
can you please post your function headers and everything before that 

``` python
    @ ...whatever
    def populate_indicators(self, dataframe: DataFrame) -> DataFrame:

```

**Comment by xmatthias** [comment]
@berlinguyinca 

it seems like it's one from your repository ... making problems with the `@staticmethod`.
did this ever happen to you when testing this or running freqshow?

``` python
@staticmethod
    def resample(dataframe, interval, factor):
```

**Comment by berlinguyinca** [comment]
these should be rewritten with the technical lib anyway. since it has a
much better resample method.

**Comment by vpotap** [comment]
yes this is from repo without any modifications

**Comment by xmatthias** [comment]
Going to close this as this bug was fixed some time ago.
