### ISSUE TITLE
Hyperopt For Strategies Does Not Work 

### ISSUE THREAD

**Issue by CryptoCoeus** [freqtrade/freqtrade-strategies#22]
When I run hyperopt command for any strat, like this :
`python3 ./freqtrade/main.py -s strategy001 hyperopt`

I am having following errors : 
`KeyError: 'ema50'` OR `KeyError: 'fisher_rsi'`

How can I run hyperopt on your algos? 

Btw, thank you for sharing 👍

**Comment by xmatthias** [comment]
Hi,

this is not how hyperopt works. please read the [documentation here](
https://github.com/freqtrade/freqtrade/blob/develop/docs/hyperopt.md) on how to configure hyperopt.

it's not ideal - but currently hyperopt requires you to modify the `hyperopt.py` file to match the strategy.
Also, sell-signal optimization is currently not implemented.

If you have further questions, please open an issue in the main repository or join the slack Chat where some experienced users are located.
