### ISSUE TITLE
GodStra/DevilStra pairlist

### ISSUE THREAD

**Issue by betogontijo** [freqtrade/freqtrade-strategies#222]
I'm having issues with optimizing GodStra/GodStraNew/DevilStra. It's probabilly the pair list I'm using. I've even tried using ".*/BTC" to try to retrieve the best ones but no success.

Is there any recomendation for pairlist using these strategies? 
Another config that I'm stugling is the max_open_trade, it is mentioned to be low, but shouldnt it be relative to the number of pair lists?

Thanks for any help

**Comment by mablue** [comment]
Sometimes when You didnt config the setting place with unfeamular or I mean hard reachable params it cant do anything but when  you use errmm easy to reach params and also settings it can be done. for example if you just use '=/R' in godstra operators it can not reach more conditions to buy things or maybe in indicators. also sometimes you shoud change the timeframe to big values. cuz small timeframes havent following a rule for example one minute time frame naver cant be more successful than a 4h tf.

**Comment by zafbangash** [comment]
In your configuration file set the pairlist to:            
             "method": "VolumePairList",
            "number_assets": 120,
            "sort_key": "quoteVolume",
            "refresh_period": 1800

then run freqtrade test-pairlist -c user_data/yourconfigurationfile 
You will get the 120 highest volume assets listed. Copy that and use that as your static pairlist (after replacing ' with ") 
Use appropriate filters and protections.

**Comment by xmatthias** [comment]
Depending on the pairlist, you'll have to optimize the strategies towards / for that pairlist - otherwise your results will probably not be pretty good.

This is true for most every strategy - as i'm yet to see one that works equally well on different pairlists (potentially with different stake currencies).

**Comment by mablue** [comment]
> Depending on the pairlist, you'll have to optimize the strategies towards / for that pairlist - otherwise your results will probably not be pretty good.
> 
> This is true for most every strategy - as i'm yet to see one that works equally well on different pairlists (potentially with different stake currencies).

The SuperPowerfull strategy is coming just wait.I'm very very buzzy nowadays but after next week I will come back with an amazing and fully deferent thing
