### ISSUE TITLE
Can be elaborated a more sustainable/better aproach of normalize fuction in GodStraNew strategy?

### ISSUE THREAD

**Issue by rongybika** [freqtrade/freqtrade-strategies#240]
## Describe your environment

  * Operating system: Windows
  * Python Version: _____ (`python -V`)
  * CCXT version: 3.7.4 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  * Strategy: GodStraNew
  
Note: All bug reports will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I'm wondering if is possible to elaborate a more better approach of normalize function in GodStraNew strategy?
Because the actual function is not producing good result when new data came in to equation.
What I found an alternative (I'm not an expert in math) could be some kind of z-score.
But could be anybody else who can have a good idea how I should try to implement a better normalization algo.

Thank you

### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  ```

**Comment by xmatthias** [comment]
data normalization on timeseries data that can be from 0.0001-0.00005 (SHIB) to 40.000-60.000 (BTC) is quite difficult - as you'd expect the result to be always roughly in the same area - but you can't really rely on it.

Anything that's using an absolute min/max should be considered wrong - as it'll change depending on the current inputs - and has an inherit lookahead bias (the scaled data will still know that 2 years from the beginning, price was 60.000).

As GodStraNew has that builtin - i do have my doubts about that strategy (it'll probably no longer work if you remove the lookahead bias) - and i'm therefore considering the removal of that strategy - as it'll promise results you cannot archive.

**Comment by rongybika** [comment]
Thank you for answer.

I forgot to tell about my ,,minor" change to the normalize function. I just ,,divided"/store the result to be separately to every coin. So SHIB have it's own min-max and BTC have it's own min-max values. I think that could be more ,,realistic" to use like this.
But I understand your concerns about the strategy, but still now I couldn't find a strategy with good results(after a lot of hyperopts).
Of course I know that the ,,working" strategies are kept under lock like top secret things. So i thought maybe I can find a working one brute forcing ,,all possible" strategies.

Thank you

**Comment by xmatthias** [comment]
the problem is not the "min-max" values per se - but the knowledge of them.

Assuming you backtest BTC/USDT for a timeperiod of 2 years.
You assign min/max as it was in this timeperiod.
This will automatically mean that no value from 2 years ago will be > 0.5 (Assuming current price of 60k, and 2 years ago of <30k).
This is one form of lookahead bias - and hyperopt will learn to more likely buy (and hold on to) pairs which had a value < 0.5 - which however is information you should not have had 2 years ago.

**Comment by rongybika** [comment]
Thank you

**Comment by algeronwaterschoot** [comment]
The "Stra" family of strategies indeed has serious problems with lookahead bias. If you want to use them, you'll have to remove the "normalization" logic, which makes use of dataframe.min() and dataframe.max(). Alternatively, you could implement a .rolling() window, but TBH, you can probably get similar functionality by using the ['/>R', '/=R', '/<R'] operators.

I also have serious doubts about the scikit performance implications of concatenating timeperiod integers onto indicator labels, resulting in CategoricalParameters with values like ['RSI-6', 'RSI-7', 'RSI-8', 'MFI-6', 'MFI-7', 'MFI-8'] and so on. I can't imagine how skopt could possibly triangulate on optimal parameters this way. And don't even get me started on how sub-indicators & trend candles are handled, e.g. 'STOCH-1-4-SMA-3'. You'll also have to do lots of retooling to be able to optimize any of the talib parameters other than "timeperiod" - which doesn't even exist for some indicators.

Perhaps we should consider archiving them, or moving them to a separate folder where people know the strategies are mothballed? Despite their major shortcomings, they do contain some elegant code sections, such as GodStraNew's "operators" logic, trend candles, Talib abstract, etc

**Comment by algeronwaterschoot** [comment]
In any case, a fix for the normalize() function would look something like this:

```
def normalize(df, lookback_candles = 200):
    rolling = df.rolling(lookback_candles)
    return (df-rolling.min())/(rolling.max()-rolling.min())
```

This tells you the percentile of each candle's talib score, as a function of the min-max of its 200 preceding candles. For example, if you plug an EMA-26 DataFrame into this function; a given candle has an EMA-26 of 88.0; the lowest EMA-26 of the 200 preceding candles is 10.0; and the highest EMA-26 of the 200 preceding candles is 110.0; then its normalized EMA-26 score will be 0.78.

I guess normalization was intended to allow you to compare incompatible indicators, such as EMA and RSI, but the implementation in the Stra family of strategies had lookahead bias...

**Comment by sabatale** [comment]
@algeronwaterschoot You meant to suggest that for the "gene_calculator", right?

```
def gene_calculator(dataframe, indicator):
    # Cuz Timeperiods not effect calculating CDL patterns recognations

.....

        # For trend operators(MA-5-SMA-4)
        elif gene_len == 4:
            # print('gene_len == 4\t', indicator)
            gene_timeperiod = int(gene[1])
            sharp_indicator = f'{gene_name}-{gene_timeperiod}'
            dataframe[sharp_indicator] = getattr(ta, gene_name)(
                dataframe,
                timeperiod=gene_timeperiod,
            )
            **return normalize_df(ta.SMA(dataframe[sharp_indicator].fillna(0), TREND_CHECK_CANDLES))**
        # For trend operators(STOCH-0-4-SMA-4)
        elif gene_len == 5:
            # print('gene_len == 5\t', indicator)
            gene_timeperiod = int(gene[2])
            gene_index = int(gene[1])
            sharp_indicator = f'{gene_name}-{gene_index}-{gene_timeperiod}'
            dataframe[sharp_indicator] = getattr(ta, gene_name)(
                dataframe,
                timeperiod=gene_timeperiod,
            ).iloc[:, gene_index]
            **return normalize_df(ta.SMA(dataframe[sharp_indicator].fillna(0), TREND_CHECK_CANDLES))**
```
