### ISSUE TITLE
Grid trading strategy 

### ISSUE THREAD

**Issue by pankajkumar** [freqtrade/freqtrade-strategies#245]
Hello folks, 

Is there any sample grid based strategy I can use in freqtrade or any guidelines on how to create one ? 

Thanks

**Comment by xmatthias** [comment]
I'm not aware of any grid trading strategy.

Freqtrade is also not really suited to be a grid bot, which assumes to place orders on both sides of the orderbook waiting to be filled.

**Comment by pankajkumar** [comment]
Here is the reference on grid trading strategy: https://www.binance.com/en/support/faq/d5f441e8ab544a5b98241e00efb3a4ab

**Comment by xmatthias** [comment]
in theory, you can probably use something like a continuous buy signal, and use [custom entry pricing](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-entry-and-exit-price-example) to define the next grid price to place the buy order.

You can work similarily when selling - by either placing the sell order immediately, or using ROI for your orders.
You'll definitely need to use some pretty sane stoploss to avoid insane losses (you'd be buying at random places, basically).

Still i believe that freqtrade is not really made for this type of strategy - but that doesn't prevent you from comming up with a way to make it work - but usually profits from a "proper" strategy will be better - as the explanation does only very lightly touch on risks involved.

There's however no such strategy available as far as i'm aware.
