### ISSUE TITLE
Strategies do not work on new versions

### ISSUE THREAD

**Issue by vladroots** [freqtrade/freqtrade-strategies#247]
Please update the code for new versions freqtrade

**Comment by xmatthias** [comment]
This is incorrect, the strategies will also work with new versions of freqtrade as long as you stick to spot markets.
Otherwise, please provide logs (and the strategy) on the error you're encountering.

As most strategies were designed for spot markets anyway, i don't see an urgent need to update all strategies.

**Comment by vladroots** [comment]
There, everywhere you need to change for new configs, changes between V2 and V3 backtesting does not work

**Comment by xmatthias** [comment]
I've just sample-backtesed a few of the strategies in this repo with the latest develop version without problems.

If you think there's a problem, please share logs of it (and with which version / strategy it's happening).

**Comment by vladroots** [comment]
how to determine which strategies for spot and which strategies for futures?

**Comment by xmatthias** [comment]
Currently all strategies provided here are for spot, except for the strategies in the `/futures` directory.

Please note that we do not guarantee profits for ANY of the provided strategies, as they are supposed to serve as sample - not as "ready to be rich" strategy.

**Comment by caglarylmz** [comment]
I tested spot strategies and didnt seen any problem.

Tested with latest freqtrade version with docker image. 
If you share your strategy and config file, I can help.

**Comment by EdvinLndh** [comment]
> This is incorrect, the strategies will also work with new versions of freqtrade as long as you stick to spot markets. Otherwise, please provide logs (and the strategy) on the error you're encountering.
> 
> As most strategies were designed for spot markets anyway, i don't see an urgent need to update all strategies.

I was also getting some errors when trying to run these strategies. For example, when running the trade command with Strategy004 I got an error saying that deprecated methods and variables are used. My very basic fix was to change 'sell' to 'exit' and 'buy' to 'entry' throughout the strategy on these methods and variables. The terminal was quite accurate in telling what the errors where.

**Comment by xmatthias** [comment]
: I was also getting some errors when trying to run these strategies. 

this will only happen if you use a configuration made for futures trades.

**Comment by daidat** [comment]
I met with the same problem because of I just use my file name as the strategy name and forget to change the python class name

**Comment by xmatthias** [comment]
All strategies have now been updated to the new interface.

As such i'll be closing this issue.
