### ISSUE TITLE
The strategy 004 cannot  run and it bring out error 


### ISSUE THREAD

**Issue by Orbazz** [freqtrade/freqtrade-strategies#251]
![Screenshot_2022-05-27-12-08-18.jpg](https://user-images.githubusercontent.com/99116118/170688551-84053ee1-2b60-4a3e-a61b-c55c91871c91.jpg)

Please the strategy cannot load  and run, what I can do or can you guide me through it

**Comment by xmatthias** [comment]
Please use text wrapped in trippel backticks (`) for logs - not pictures of a screen where the error is barely readable.

it seems like your strategy is not available. With the provided information (no command that's run, how did you setup / clone the strategy repository, where is the strategy file located) - there's unfortunately very little to nothing to do for us to help you (other than maybe pointing to the documentation ... which i hope you've read already).

**Comment by Orbazz** [comment]
> Please use text wrapped in trippel backticks (`) for logs - not pictures of a screen where the error is barely readable.
> 
> it seems like your strategy is not available. With the provided information (no command that's run, how did you setup / clone the strategy repository, where is the strategy file located) - there's unfortunately very little to nothing to do for us to help you (other than maybe pointing to the documentation ... which i hope you've read already).
