### ISSUE TITLE
i cant run or load the strategy

### ISSUE THREAD

**Issue by Orbazz** [freqtrade/freqtrade-strategies#252]
## Describe your environment

  * Operating system: windows 10
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  * Strategy: _____
  
Note: All bug reports will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____

  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.
**"""freqtrade.exceptions.OperationalException:** Impossible to load Strategy 'BBRSINavieStrategy'. This class does not 
exist or contains Python code errors.
freqtrade    | 2022-05-27 16:44:53,620 - freqtrade.worker - INFO - Starting worker 2022.4.2
freqtrade    | 2022-05-27 16:44:53,620 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
freqtrade    | 2022-05-27 16:44:53,651 - freqtrade.loggers - INFO - Verbosity set to 0
freqtrade    | 2022-05-27 16:44:53,661 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
freqtrade    | 2022-05-27 16:44:53,729 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
freqtrade    | 2022-05-27 16:44:53,740 - freqtrade.configuration.configuration - INFO - Dry run is enabled
freqtrade    | 2022-05-27 16:44:53,800 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
freqtrade    | 2022-05-27 16:44:53,810 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
freqtrade    | 2022-05-27 16:44:54,214 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
freqtrade    | 2022-05-27 16:44:54,226 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
freqtrade    | 2022-05-27 16:44:54,230 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
freqtrade    | 2022-05-27 16:44:54,376 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
freqtrade    | 2022-05-27 16:44:54,409 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.      
freqtrade    | 2022-05-27 16:44:54,420 - freqtrade.freqtradebot - INFO - Starting freqtrade 2022.4.2
freqtrade    | 2022-05-27 16:44:54,830 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'BBRSINavieStrategy'. This class does not exist or contains Python code errors.
freqtrade    | 2022-05-27 16:44:54,839 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade    |     worker = Worker(args)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade    |     self._init(False)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade    |     self.freqtrade = FreqtradeBot(self._config)
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 62, in __init__
freqtrade    |     self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
freqtrade    |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
freqtrade    |     strategy: IStrategy = StrategyResolver._load_strategy(
freqtrade    |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 286, in _load_strategy
freqtrade    |     raise OperationalException(
freqtrade    | freqtrade.exceptions.OperationalException: Impossible to load Strategy 'BBRSINavieStrategy'. This class does not exist or contains Python code errors."

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
Well it's exactly what it says - there is no class named `BBRSINavieStrategy` in the strategy path (by `default user_data/strategies`.

**Comment by xmatthias** [comment]
You can learn how to create strategies yourself by reading the [strategy documentation](https://www.freqtrade.io/en/stable/strategy-customization/).

I'd also strongly suggest to read (or at least fly over) the full documentation - it will avoid a lot of needless questions and frustrations, as you'll know what you can find in the documentation.
