### ISSUE TITLE
unable to load strategy issue

### ISSUE THREAD

**Issue by Orbazz** [freqtrade/freqtrade-strategies#253]
## Describe your environment

  * Operating system: _window 11___
  * Python Version: __3.10___ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____2022.4 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  * Strategy: _ BBRSINaiveStrategy____
  
Note: All bug reports will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____

  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```freqtrade    | 2022-05-29 12:15:51,088 - freqtrade.strategy.hyper - INFO - Found no parameter file.
freqtrade    | 2022-05-29 12:15:51,092 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
freqtrade    | 2022-05-29 12:15:51,104 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
freqtrade    | 2022-05-29 12:15:51,111 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
freqtrade    | 2022-05-29 12:15:51,118 - freqtrade.commands.trade_commands - ERROR - DEPRECATED: Using 'sell_profit_only' moved to 'exit_profit_only'.
freqtrade    | 2022-05-29 12:15:51,124 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade    |     worker = Worker(args)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade    |     self._init(False)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade    |     self.freqtrade = FreqtradeBot(self._config)
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 63, in __init__
freqtrade    |     self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
freqtrade    |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
freqtrade    |     strategy: IStrategy = StrategyResolver._load_strategy(
freqtrade    |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 284, in _load_strategy
freqtrade    |     return StrategyResolver.validate_strategy(strategy)
freqtrade    |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 177, in validate_strategy
freqtrade    |     warn_deprecated_setting(strategy, 'sell_profit_only', 'exit_profit_only', True)
freqtrade    |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 296, in warn_deprecated_setting
freqtrade    |     raise OperationalException(errormsg)
freqtrade    | freqtrade.exceptions.OperationalException: DEPRECATED: Using 'sell_profit_only' moved to 'exit_profit_only'.

**Comment by xmatthias** [comment]
If you're using futures markets - then you'll have to migrate the strategy to the new version (as stated in the [documentation](https://www.freqtrade.io/en/stable/strategy_migration/)).

As most strategies provided here are NOT made for futures markets - they are currently not migrated (intentionally, to keep compatibility with old versions for now), and this task falls to the user (if they assume the same strategy would work on futures markets).

There are a few futures strategies (in the futures directory) which are using the new interface already.

 The one you're using seems to not be part of this repository - so please stick to the documentation, which will teach you how to write a strategy with the uptodate interface.

**Comment by Orbazz** [comment]
okay, thanks
