### ISSUE TITLE
Pump Detection

### ISSUE THREAD

**Issue by vladroots** [freqtrade/freqtrade-strategies#257]
Hello! Suggest a strategy for determining pumps with a dynamic list of coins. So that the strategy works only before the pump.
![pump](https://user-images.githubusercontent.com/64924193/179238447-696ec8bd-c134-4680-93c3-23360581a7d8.jpg)

**Comment by xmatthias** [comment]
I guess what you can use is the [`RangeStabilityFilter`](https://www.freqtrade.io/en/stable/plugins/#rangestabilityfilter) - which allows you to filter out pairs which broke a certain range (for example the one below).

in that particular case, you might even get away with a SMA/EMA approach - and if price is a few 100% above the average, it had a bump quite recently. It's then ultimately up to you to finetune it to values that make sense for your strategy.

**Comment by vladroots** [comment]
how should the value of RangeStabilityFilter be set like on the screenshot?
What value defines out of bounds? If you put, for example, 10%, then many coins can go beyond these limits.

![65466](https://user-images.githubusercontent.com/64924193/179812580-566e89c8-dfaa-4ff0-ad26-8dc854e05551.jpg)

**Comment by xmatthias** [comment]
That's correct - it'll depend on your definition of a spike. if we define a spike as "more than 50%" - then your example is not a spike - just a move.

**Comment by vladroots** [comment]
It turns out that you need to test "min_rate_of_change": 0.5, do I understand correctly?
And how can you catch such movements in 20-30%?

**Comment by xmatthias** [comment]
well you can set it to 0.2 ... but then it'll obviously also filter out other pairs with similar, non-spike moves.

You can also attempt to come up with some other solution to use as strategy guard (like - move within 1 candle or so - but it'll all depend on your personal definition of bump.

**Comment by vladroots** [comment]
The only thing I don’t understand is how a non-example of 100 coins will be determined which pump will make. Can you suggest a config and strategy for the test?

**Comment by vladroots** [comment]
How to set up movement within 1 candle?

**Comment by xmatthias** [comment]
you can probably detect bumps within one candle by comparing either high with low, or open with close.
