### ISSUE TITLE
how to get the day of the week?

### ISSUE THREAD

**Issue by Alvised** [freqtrade/freqtrade-strategies#263]
hi i'm new to freqtrade and python, i'm learning but i don't know how to get the day of the week.
 for example if i  don't want the bot to trade on sunday or use a different strategy on monday.. what code i have to write to have the time of the day from the unix code? It's would be perfect if i got a number from 1 to 7, to identificate the day of the week.
 Hope you can help me

**Comment by xmatthias** [comment]
most likely - [pandas `.dt.dayofweek`](https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.dayofweek.html).


Using it with freqtrade, this would then be `(dataframe['date'].dt.dayofweek != 6)`
Please check the documentation which number represents which date.

In general - i'd also suggest to search things like this with "pandas " as prefix - so "pandas dayof week" will basically lead you almost directly to the above documentation page.

**Comment by Alvised** [comment]
thank you! it work perfectly!
