### ISSUE TITLE
buy when value drops by x % within x timeframe

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade-strategies#264]
*For requestion a new strategy. Please use the template below.*  
*Any strategy request that does not follow the template will be closed.*
I'm not looking for a way to trade per se. I just want an automated way to buy BTC. Freqtrade will never sell. It will simply buy when the conditions are met.

## Step 1: What indicators are required?
I'm not sure which indicator is more suitable for this strategy. Please advise.

## Step 2: Explain the Buy Strategy
Since I don't expect freqtrade to ever sell, the buy strategy is pretty simple. For example: If the BTC value drops by 3% within a timeframe of 24 hours, buy $100 worth of BTC. That's it. I just need to define these 3 values.

- the percentage the value drops
- the timeframe that the value dropped within
- the amount of BTC to buy (I know that's defined in config.json)

## Step 1: Explain the Sell Strategy
No sell strategy. This is just for investing in BTC.

## Source
I'm sure someone though of this, so if a strategy already exists for this, please point me to it.

Thanks

**Comment by xmatthias** [comment]
Freqtrade is not really made/designed for accumulating assets. 
It's made and designed for trading - which means entering and exiting positions (more or less frequently).

There's more than the sell-signal that act as exit signals (stoploss, ROI, ...) - so you'll need to work around these (by setting them to very high numbers).

you can probably get around this somewhat by using the [position adjustment](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) callback.

Doing a "% value dropped" should be pretty simple by comparing with the prior candle

something around `(dataframe['close'] < dataframe['close'].shift(1) * 0.97)` should suffice - assuming you're using daily candles.

If you need smaller timeframes, then the shift will obviously need to be adjusted for that.

**Comment by aristosv** [comment]
Well, I guess eventually I would sell at some point, but I would do it manually.

I understand freqtrade is not meant to accumulate assets, but it would make it sooo easy to perform these tasks (and much more):

- buy the dip without having to manually monitor assets value
- track profit/loss on open positions (/status table) and historically (/daily, /weekly, /monthly)
- easily and quickly sell when I decide to, without having to do it on the exchange. (/forceexit <trade_id>)

It would be very hard for me to understand and create a new strategy from scratch that does what I want.

Since there is no existing strategy that can do what I want, how about a strategy that simply buys the dip? Maybe I can define some values in there that would make it work as closely as possible to what I want to do?

**Comment by xmatthias** [comment]
There's several strategies that do such things (BinHV45, ...) - but often combining different indicators / approaches for better results.
Best look around the repository for inspiration - but the moment you have some concrete idea, you will need to learn how to modify a strategy (the [documentation](https://www.freqtrade.io/en/stable/strategy-customization/) is a good place to start learning this).

While you may not need/want to write it from scratch - you should still be familiar with the concepts - and with how things work to properly look at this in detail.

**Comment by aristosv** [comment]
thank you
