### ISSUE TITLE
obtain the bought price or the current profit

### ISSUE THREAD

**Issue by Alvised** [freqtrade/freqtrade-strategies#267]
hi i bother you for the last time,at least for this month,i promise :)
I need to know the price the bot bougth a pair and compare it with the current price(  dataframe['last_price']  ).. the only thing  i've seen in the documentation is:
```
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime, current_rate: float, current_profit: float, **kwargs) -> float:

        # once the profit has risen above 10%, keep the stoploss at 7% above the open price
        if current_profit > 0.10:
            return stoploss_from_open(0.07, current_profit, is_short=trade.is_short)

        return 1
```
from the current profit and the current rate i could calculate the price i entered the trade(is there a more direct way?)..but i tried and tried and i'm not capable of extracting current_profit in a way i can use it in combination with dataframe['last_price'] for example:     dataframe['last_price']*current_profit

**Comment by xmatthias** [comment]
you can use `trade.open_rate` to get the entry price.

In case of multiple entries, this will be the average rate the bot entered the remaining position.

**Comment by Alvised** [comment]
thank you again!
