### ISSUE TITLE
How to set first stage when profit>3%,  sell 50% position, when profit>5% ,sell the remain 50% position??

### ISSUE THREAD

**Issue by gitscamI** [freqtrade/freqtrade-strategies#269]
How to set first stage when profit>3%,  sell 50% position, when profit>5% ,sell the remain 50% position??  anybody can help? thanks

**Comment by gitscamI** [comment]
Thank you very much, I get  something !

**Comment by gitscamI** [comment]
the fllowing is my setup, is it correct??
  def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs) -> 'Optional[Union[str, bool]]':
      
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()
        if  current_profit > 0.03 and  current_profit < 0.05:
            return 'tp_1_exit'
        if   current_profit >= 0.05:
            return 'tp_2_exit'

        return None        

   def adjust_trade_position(self, trade: 'Trade', current_time: 'datetime',
                              current_rate: float, current_profit: float, min_stake: Optional[float],
                              max_stake: float, **kwargs) -> 'Optional[float]':
      
        if current_entry_profit  > 0.03 and current_entry_profit <0.05:

            return -(trade.stake_amount / 2)

        return None

**Comment by xmatthias** [comment]
if `custom_exit` returns anything other than None - then it'll result in a full exit. 

you'll have to remove the first condition in that method - and rely on the "adjust trade position" instead.

**Comment by gitscamI** [comment]
in this situation,  it had only sold 50% position when profit reached 3%,   how to setup sell the remain 50% position when profit reach 5%??

**Comment by xmatthias** [comment]
The combination of adjust_trade-position with custom_exit will do this.

Implementing the above suggestions into your code:

```
  def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs) -> 'Optional[Union[str, bool]]':
      
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()
        if   current_profit >= 0.05:
            return 'tp_2_exit'

        return None        

   def adjust_trade_position(self, trade: 'Trade', current_time: 'datetime',
                              current_rate: float, current_profit: float, min_stake: Optional[float],
                              max_stake: float, **kwargs) -> 'Optional[float]':
      
        if current_profit  > 0.03 and current_profit <0.05 and trade.nr_of_successful_exits == 0:

            return -(trade.stake_amount / 2)

        return None
```

** untested - but from a conceptual perspective it looks good.

**Comment by gitscamI** [comment]
thank you very much ,I will test it ....

**Comment by gitscamI** [comment]
it donesnt work.   I check the backtesting source code   file backtesting.py line no 498:
`def _get_adjust_trade_entry_for_candle(self, trade: LocalTrade, row: Tuple
                                           ) -> LocalTrade:
        current_profit = trade.calc_profit_ratio(row[OPEN_IDX])
        min_stake = self.exchange.get_min_pair_stake_amount(trade.pair, row[OPEN_IDX], -0.1)
        max_stake = self.exchange.get_max_pair_stake_amount(trade.pair, row[OPEN_IDX])
        stake_available = self.wallets.get_available_stake_amount()
        stake_amount = strategy_safe_wrapper(self.strategy.adjust_trade_position,
                                             default_retval=None)(
            trade=trade,  # type: ignore[arg-type]
            current_time=row[DATE_IDX].to_pydatetime(), current_rate=row[OPEN_IDX],
            current_profit=current_profit, min_stake=min_stake,
            max_stake=min(max_stake, stake_available))

        # Check if we should increase our position
        if stake_amount is not None and stake_amount > 0.0:

            pos_trade = self._enter_trade(
                trade.pair, row, 'short' if trade.is_short else 'long', stake_amount, trade)
            if pos_trade is not None:
                self.wallets.update()
                return pos_trade

        return trade`

when return stake_amount <0, it will be pass.  is it ???

**Comment by xmatthias** [comment]
i have no clue what you're talking about  (or what verison you're using). L498 does something completely different - which suggests that you're on an old version.

**Comment by gitscamI** [comment]
Yes , sorry ,I found using the older version ,now updated it work.thank you
