### ISSUE TITLE
whice pairs backtesting for Strategy001--Strategy005?

### ISSUE THREAD

**Issue by gitscamI** [freqtrade/freqtrade-strategies#270]
I see a result table for Free trading strategies, when I open the strategy, I don't find no trades pairs in it , so I want to ask which pairs for these backtesting data?

**Comment by xmatthias** [comment]
uh i don't remember (or never knew).

these results are from 2018 - with a freqtrade version from 2018 - so if the results will be identical now (we improved a ton in the last 4 years) is not certain (they'd sure be slightly different - by how much is tough to say (market conditions also changed between 2018 and now).

The table should probably be removed - i don't think it provides much value as is.

**Comment by xmatthias** [comment]
The original results for these strategies can be seen in their responsive PR's (#1, #2, #3, #4, #5 ).

The results will however only serve a demonstrative purpose on how the strategy can be expected to perform (number of trades, ...). Effective performance will however heavily depend on too many factors to make such a static result actually reliable.
