### ISSUE TITLE
How to config two or more stategies to run on one server?

### ISSUE THREAD

**Issue by gitscamI** [freqtrade/freqtrade-strategies#275]
I write two freqtrade strategies, I had run one strategy on a docker , how to setup I can run the two strategies at the sametimes??

**Comment by xmatthias** [comment]
One bot instance runs one strategy.

you can however run [multiple bots](https://www.freqtrade.io/en/latest/advanced-setup/#running-multiple-instances-of-freqtrade).

Also, please note that this is the strategy repository - basic support questions are wrong here.
