### ISSUE TITLE
External Signal provider

### ISSUE THREAD

**Issue by jryals579** [freqtrade/freqtrade-strategies#278]
Can I incorporate a paid subscription of trade signals to fully automate my trades ? I have used this signal provider on another bot but I rather try to use FreqTrade . The provider provided me an API key ( they also send me these signals to Telegram as well  if that matters ? So and hoping for some insight if this is something freqtrade can ?

**Comment by xmatthias** [comment]
Freqtrade strategies are just python code - so whatever you can code / connect to in python, should be possible with freqtrade, assuming some coding knowledge.

If it's a paid subscription - it's clearly not something that's built into freqtrade - but i don't see why you can't build something into a strategy.

**Comment by jryals579** [comment]
Appreciate it . I found this on their site and I was curious if anyone else had attempted this before? I guess I can try to learn some python 

https://www.mininghamster.com/api/

I guessing Freqtrade doesn’t plan to have any providers that can fully integrate within the solution . The platform I thought was developed so not having to do manual trades . I know/ used other crypto bots and they supported this provider along with 4-6 others.

**Comment by xmatthias** [comment]
Consuming an API is something most python courses will teach almost immediately.
Freqtrade is clearly aimed at users who are also willing to do some coding. 

If you're looking at a "click twice, get rich" solution, this is the wrong project for you.

Blindly using some shady signals from random providers is also not it's the goal of freqtrade.
We don't restrict this usage - and integrating with an API is quite easy and straightforward, which most (medium-good) python courses will teach very early on.


There's 100ds of so-called signal providers out there - with varying quality of signals.
We'll neither favor any of these - nor support any of these actively.

Freqtrade is a free, open source bot, where strategies run in pure python.
As such, the whole python ecosystem is open to be used in a strategy.

As it's pure python code, signal-provider could therefore either
* provide a python package to easily integrate
* provide sample code (in python) to integrate
* provide freqtrade sample strategies / configuration how to use their signals.
