### ISSUE TITLE
cannot use the timeframe i want

### ISSUE THREAD

**Issue by Alvised** [freqtrade/freqtrade-strategies#292]
hi, i've done my strategy based on HourBasedStrategy ([https://github.com/freqtrade/freqtrade-strategies/blob/main/user_data/strategies/HourBasedStrategy.py](url)

the only difference between mine and the original is that when in the permitted hours it doesn't buy automatically but it checks ema and rsi.. i've seen that for the best results i had to check thoose indicators in a 5m timeframe, i backtested with --timeframe 5m with no problem.. 
but now that i'm doing live trading with dry run it goes automatically to 1h,no matter if i set timeframe=5m in the strategy..
I tried other strategies and they correctly use the 5m timeframe. to be sure i did a backtesting of my hourbasedstrategy without "--timerange" and it goes to 1hour, so it's someting inside the strategy

How can i fix this?

**Comment by xmatthias** [comment]
the strategy itself will most likely be running on 5m - however the HourBased strategy itself is using `dataframe['date'].dt.hour` - which will return the same number for the whole hour.

the timeframe is therefore also built into the strategy itself.

If the startup logs still show "timeframe=1h" instead of 5m - then the 1h timeframe is most likely in your configuration - which will overwrite the strategy settings.

**Comment by Alvised** [comment]
what file i have to check? i searched the config.json and the hourbasedstrategy, json of  and i didn't found the word timeframe o 1h anywhere. this is my strategy configuration(i erased all the values)
`{
  "strategy_name": "HourBasedStrategy",
  "params": {
    "trailing": {
      "trailing_stop": 
      "trailing_stop_positive": 
      "trailing_stop_positive_offset": 
      "trailing_only_offset_is_reached": 
    },
    "buy": {
      "buy_hour_maxd": , 
     
      "buy_hour_mind": ,
      
    },
    "sell": {
      "sell_hour_maxv": 
    },
    "protection": {},
    "roi": {
      "0": 0.
      "14": 0.0,
      "68": 0.0,
      "168": 0
    },
    "stoploss": {
      "stoploss": 
    }
  },
  "ft_stratparam_v": 1,
  "export_time": "2023-02-15 00:01:09.635634+00:00"
}`

and theese are the voices in the config.json(all value erased)
`
{
    "max_open_trades": 
    "stake_currency": 
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 
    "fiat_display_currency": 
    "dry_run": false,
    "dry_run_wallet": 
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": 
        "key":       "secret": 
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        "",
        
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 300
        }
    ],
    "telegram": {
        "enabled": true,
        "token": ,
        "chat_id": 
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": 
        "listen_port": 
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": ",
        "ws_token": "
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": ",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}`


the 1h timeframe is confirmed in terminal ( with:
freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1h
) and by the telegram bot

**Comment by xmatthias** [comment]
well the full startup logs will contain the info where the 1h is comming from (it's noted there if the config overwrites the strategy).

By itself, it sounds like `timeframe = "1h"` is still in the strategy file. 
maybe you have the same strategy twice in your directory (check with `freqtrade list-strategies`) - or you forgot to safe the file ...

**Comment by froggleston** [comment]
No response in 6+ months. Closing.
