### ISSUE TITLE
BB_RSI_ATR

### ISSUE THREAD

**Issue by sandervdhave** [freqtrade/freqtrade-strategies#297]
Firstly, thanks for this great app and all the documentation. It really helps!

I created a strategy in Tradingview with pretty nice results. But there is a delay on the communication with WunderTrading. So i am looking to build the strategy in Freqtrade. Hopefully i can use hyperopt to make this strategy even better. I am not a programmer, so i could really use some help.

Thanks!

## Step 1: What indicators are required?

I need 3 indicators:
- Bollinger Bands
- RSI
- ATR

## Step 2: Explain the Buy Strategy

Bollinger Bands:
![Schermafbeelding 2023-03-06 om 09 20 08](https://user-images.githubusercontent.com/41057106/223055660-bd024f2f-9888-41e0-a32c-485c829d1a4b.png)
Length: 11
stdev: 1.8

RSI:
![Schermafbeelding 2023-03-06 om 09 23 44](https://user-images.githubusercontent.com/41057106/223055904-87a6abbc-51f0-4714-80c0-0b0fc24b9caf.png)
Length: 19

ATR:
![Schermafbeelding 2023-03-06 om 09 24 36](https://user-images.githubusercontent.com/41057106/223056098-a5a0a936-6932-47ed-b725-6197bf0c523a.png)
Length: 20
SL multiplier: 3.2
TP multiplier: 3.2

Condition for enter_long:
1. The close price of the candle should be below the lower bollingerband
2. The RSI should be below 25
3. Than wait for a bullish candle (wait max. 8 candles)
4. Bullish candle = close > open & close > high.shift(1)
5. Save the ATR value on the entry candle

## Step 1: Explain the Sell Strategy

Condition for exit_long:
1. Use ATR value of the entry candle.
2. place stoploss 3.2 x ATR value below the entry price.
3. place take profit 3.2 x ATR value above the entry price.
4. Wait at least 8 candles for a new entry.

## Source

Found this strategy on YouTube by user 'Serious Backtester'.
What come from this strategy? Cite your source:
* https://www.youtube.com/watch?v=1ZHaHd0W9ec&t=302s

I have ade the strategy in TradingView and it gives pretty good results. But i want to use Freqtrade because there is a delay between Tradingview and Wundertrading. Also i want to use hyperopt to optimalise the strategy.

I have been working on it, but i am not a programmer and i am stuck. This is what i've got:
```
# --- Do not remove these libs ---
from freqtrade.strategy import IStrategy
from pandas import DataFrame
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib
# --------------------------------

class BB_RSI_ATR(IStrategy):

    INTERFACE_VERSION: int = 3
    # Minimal ROI designed for the strategy.
    # adjust based on market conditions. We would recommend to keep it low for quick turn arounds
    # This attribute will be overridden if the config file contains "minimal_roi"
    minimal_roi = {
        "0": 0.1
    }

    # Optimal stoploss designed for the strategy
    stoploss = -0.25

    # Optimal timeframe for the strategy
    timeframe = '5m'

    # Create custom dictionary
    custom_info = {}

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        print('populate indicators')

        # Bollinger Bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=11, stds=1.8)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']

        # RSI
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=19)

        # ATR
        dataframe['atr'] = ta.ATR(dataframe, timeperiod=20)

        print(dataframe)

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        condition = (
            (dataframe['rsi'] < 25) &
            (dataframe['close'] < dataframe['bb_lowerband'])
        )
        
        print('condition?')
        condition_rows = dataframe[condition]
        print(condition_rows)

        is_bullish = (
            (dataframe['open'] < dataframe['close']) &
            (dataframe['close'] > dataframe['high'].shift(1))
        )

        print('bullish?')
        bullish_rows = dataframe[is_bullish]
        print(bullish_rows)

        dataframe.loc[
            (
                condition.rolling(window=9, min_periods=1).sum() > 0 &  # RSI and BB condition within the last 9 candles
                (is_bullish)   # bullish condition
            ),
            'enter_long'] = 1
        
        print('entry candles')
        entry_rows = dataframe[dataframe['enter_long'] == 1]
        print(entry_rows)


        print('enter long')
        print(dataframe)

        # Store ATR value at the time of entry in the custom_info dictionary
        if not entry_rows.empty:
            entry_index = entry_rows.index[-1] # get index of the last entry row
            self.custom_info['entry_atr'] = entry_rows.loc[entry_index, 'atr']
            self.custom_info['entry_price'] = entry_rows.loc[entry_index, 'open']
            
        return dataframe
        
    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        # Get the ATR value at the time of entry from the custom_info dictionary
        entry_atr = self.custom_info.get('entry_atr')
        entry_price = self.custom_info.get('entry_price')

        dataframe.loc[
            (
                (dataframe['close'] <= entry_price - entry_atr * 3.2) |  # Use ATR value as stop loss
                (dataframe['close'] >= entry_price + entry_atr * 3.2)    # Use ATR value as take profit
            ),
            'exit_long'] = 1
    
        print('exit candles')
        exit_rows = dataframe[dataframe['exit_long'] == 1]
        print(exit_rows)

        print('exit long')
        print(dataframe)

        return dataframe
```

**Comment by xmatthias** [comment]
`entry_index = entry_rows.index[-1] # get index of the last entry row` (and all subsequent code depending on that) in a populate_* method will lead to automatic "un-backtestability" - as it's looking into the future during backtesting, and is one of the common [strategy gotchas](https://www.freqtrade.io/en/stable/strategy-customization/#common-mistakes-when-developing-strategies).


Something similar goes with `self.custom_info['entry_atr'] = entry_rows.loc[entry_index, 'atr']` - which will effectively not be populated, or will be populated with only one data (not with data for different pairs, letalone trades).
For such logic, best use [callbacks](https://www.freqtrade.io/en/latest/strategy-callbacks/) - based on the logic, most likely the `custom_exit()` callback.

**Comment by sandervdhave** [comment]
Hey Matthias,
Thanks! I am a real beginner, so every bit of feedback is useful. I did try to use the callbacks, but i can't get it to work yet. So still going to work on it.

I think i can see in the plotted data that my entry-method does not enter a long position on a bullish candle. Can you tell me how that happens? I've tried to define the bullish candle in the is_bullish condition.

**Comment by sandervdhave** [comment]
Ok, i have been working on it for a few hours. Getting into a nice learning curve ;) This is the code i have now:

`# --- Do not remove these libs ---
from freqtrade.strategy import IStrategy
from pandas import DataFrame
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib
from freqtrade.exchange import timeframe_to_prev_date
# --------------------------------

class BB_RSI_ATR(IStrategy):

    INTERFACE_VERSION: int = 3
    # Minimal ROI designed for the strategy.
    # adjust based on market conditions. We would recommend to keep it low for quick turn arounds
    # This attribute will be overridden if the config file contains "minimal_roi"
    minimal_roi = {
        "60": 0.01,
        "30": 0.02,
        "0": 0.03
    }
    
    use_custom_exit = True

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.10
    trailing_stop = True

    # Optimal timeframe for the strategy
    timeframe = '5m'

    # Create custom dictionary
    custom_info = {}

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        print('populate indicators')

        # Bollinger Bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=11, stds=1.8)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']

        # RSI
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=19)

        # ATR
        dataframe['atr'] = ta.ATR(dataframe, timeperiod=20)

        print(dataframe)

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        #Long Conditions
        long_outbreak = (
            (dataframe['rsi'] < 25) &
            (dataframe['close'] < dataframe['bb_lowerband'])
        )

        bullish = (
            (dataframe['open'] < dataframe['close']) &
            (dataframe['close'] > dataframe['high'].shift(1))
        )
        
        # Enter_Long
        dataframe.loc[
        (
            (long_outbreak.rolling(window=9, min_periods=1).sum() > 0) &  # RSI and BB condition within the last 9 candles
            (bullish)   # bullish condition on the current candle
        ),
        'enter_long'] = 1
        
        print('entry candles')
        entry_candle = dataframe[dataframe['enter_long'] == 1]
        print(entry_candle)


        print('enter long')
        print(dataframe)

            
        return dataframe
        
    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        dataframe.loc[
            (
            ),
            'exit_long'] = 1
        
        return dataframe
    
    def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float, current_profit: float, **kwargs):

        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        print(dataframe)  # Add this line to check if the dataframe is empty
        last_candle = dataframe.iloc[-1].squeeze()

        # Check if we have an open trade
        if trade:
            # Get the entry candle of the current trade
            entry_candle = trade.open_date_utc

            # Calculate the ATR value for the entry candle
            entry_atr = dataframe.loc[dataframe['date'] == entry_candle, 'atr'].values[0]

            # Check if the current close price is above 1.5 times the entry ATR value
            if last_candle['close'] > entry_atr * 1.5:
                return 'atr_exit_signal'

            # else, hold
            return None`

When backtesting there is backtesting data but also this error repeatedly:

2023-03-07 21:53:15,066 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error index 0 is out of bounds for axis 0 with size 0 calling <bound method BB_RSI_ATR.custom_exit of <BB,RSI,ATR.BB_RSI_ATR object at 0x7f57fb252740>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/user_data/strategies/BB,RSI,ATR.py", line 106, in custom_exit
    entry_atr = dataframe.loc[dataframe['date'] == entry_candle, 'atr'].values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

Is there someone who could help me to get this custom_exit in order?

**Comment by xmatthias** [comment]
the way you're using entry_candle will be fluky though in backtesting it should work -and will definitely fail in live).

`trade.open_date_utc` is the time the trade opened - which in live, is not necessarily an exact candle date (even if it is - it'll still contain milliseconds, so comparing it with `==` to a candle date won't work).

instead, use the method shown [in the docs](https://www.freqtrade.io/en/latest/strategy-advanced/#dataframe-access) - which first rounds the date to the nearest candle date, and then accesses the candle.

**Comment by sandervdhave** [comment]
Thanks for pointing me in the right direction. The strategy works like it supposed to. Now i am going to try the Hypropt. Fingers crossed!
