### ISSUE TITLE
Momentum Strategy

### ISSUE THREAD

**Issue by zeytindali83** [freqtrade/freqtrade-strategies#298]
Hello i try to make momentum strategy from tradingview;

```
strategy("Momentum Strategy", overlay=true)
length = input(12)
price = close
momentum(seria, length) =>
	mom = seria - seria[length]
	mom
mom0 = momentum(price, length)
mom1 = momentum( mom0, 1)
if (mom0 > 0 and mom1 > 0)
	strategy.entry("MomLE", strategy.long, stop=high+syminfo.mintick, comment="MomLE")
else
	strategy.cancel("MomLE")
if (mom0 < 0 and mom1 < 0)
	strategy.entry("MomSE", strategy.short, stop=low-syminfo.mintick, comment="MomSE")
else
	strategy.cancel("MomSE")
```

i can make first momentum indicator, but dont understand second one.
its momentum's momentum, i did this but didnt work,

```
dataframe['mom0'] = ta.MOM(dataframe, timeperiod=12)
dataframe['mom1'] = ta.MOM((ta.MOM(dataframe, timeperiod=12)), timeperiod=1)
```

can you please help me

**Comment by xmatthias** [comment]
well the problem with pinescript is that it's not really fully open source - and we've observed time and time again that results do actually differ when transferred 1:1 to python.

Your 2nd call definitely also has a syntax problem.
freqtrade strategies usually use the abstract interface (`import talib.abstract as ta`)

that means, the first parameter is expected to be a dataframe (ta.MOM returns a series).
so 
```
dataframe['mom1'] = ta.MOM((ta.MOM(dataframe, timeperiod=12)), timeperiod=1)
```
would have to become 
```
dataframe['mom1'] = ta.MOM(dataframe, timeperiod=1, price='mom0')
```
.
now i'm not sure on the internal calculation of MOM ... 

Ad hock, i'd say it's as simple as the following based on the tradingview code... but it's untested so take with caution.

```
lag = 12
dataframe['mom0'] = dataframe['close'] - dataframe['close'].shift(12)
dataframe['mom1'] = dataframe['mom0'] - dataframe['mom0'].shift(12)
```

I think both options should work - now if they yield what you expect is an entirely different question ...

**Comment by xmatthias** [comment]
i've got no clue what `high+syminfo.mintick` is supposed to mean. Best look through the tradingview / pine documentation to find out.

**Comment by alexeyromanko** [comment]
@zeytindali83 hey! do you complete your adaptation or need help with?
