### ISSUE TITLE
incorrect times displayed in FreqUI

### ISSUE THREAD

**Issue by BigJonMMXX** [freqtrade/freqtrade-strategies#301]
Hi, im trying out a few different strategies... i make sure system is clean/reset before new strategy...
When i run a bot, and look at FreqUI - Trade - General, i see this:
Bot start date: 2023-05-15 07:45:51 (UTC)
First trade opened: 2023-05-15 05:45:54 (UTC)

This has happened many times - the bot starts 2 hours *after* the first trade ???????????????

(My local time is 9:45am = 7:45utc)

**Comment by BigJonMMXX** [comment]
could it be the bot start is my local time ? and the trade opened is the exchange time ?   i dont think so as binance exchange is about 8 timezones away from me...

**Comment by xmatthias** [comment]
Nice catch, will be fixed with the next freqtrade version (it's not a UI bug, but a bug in the data that's returned).
