### ISSUE TITLE
AlphaTrend Strategy

### ISSUE THREAD

**Issue by yazbuz** [freqtrade/freqtrade-strategies#302]
hi. I am trying to create hyperoptable strat file of alphatrend strategy which I found from issiu page. (https://github.com/freqtrade/freqtrade/issues/7182) The indicator has 2 paremeters for optimization. those are ap and coeff. i tried something. Can u help me? Where is my mistake? 
ERROR - The 'buy' space is included into the hyperoptimization but no parameter for this space was not found in your Strategy. Please make sure to have parameters for this space enabled for optimization or remove the 'buy' space from hyperoptimization.

    INTERFACE_VERSION: int = 3

    # Buy hyperspace params:
    buy_params = {
        "buy_ap": 14,
        "buy_coeff": 1}
    # Sell hyperspace params:
    sell_params = {
        "sell_ap": 5,
        "sell_coeff": 2}

    minimal_roi = {
        "0": 10
    }

    can_short: bool = True

    stoploss = -0.99

    timeframe = "15m"

    buy_ap: CategoricalParameter([14, 15, 16], default=14, space = "buy", optimize=True, load=True)
    buy_coeff: CategoricalParameter([0.5, 0.8], default=1, space="buy", optimize=True, load=True)

    sell_ap: IntParameter(10, 11, default=14, space="sell", optimize=True, load=True)
    sell_coeff: DecimalParameter(0.5, 0.7, default=1, space="sell", optimize=True, load=True)

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        for ap in self.buy_ap.value:
            for coeff in self.buy_coeff.value:
                dataframe[f'k1_{ap}_{coeff}'] = self.generateAlphaTrend(
                    dataframe, ap, coeff)['k1']
                dataframe[f'k2_{ap}_{coeff}'] = self.generateAlphaTrend(
                    dataframe, ap, coeff)['k2']

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe[f'k1_{self.buy_ap.value}_{self.buy_coeff.value}']),
                  (dataframe[f'k2_{self.buy_ap.value}_{self.buy_coeff.value}']))
                #   (qtpylib.crossed_above(dataframe['k1'] , dataframe['k2']))
                #    (dataframe[f"k1_{self.buy_ap.value}_{self.buy_coeff.value}"] > dataframe[f"k2_{self.buy_ap.value}_{self.buy_coeff.value}"]) &
                #    (dataframe['signal'].shift(1) == 'sell')
            ),
            'enter_long',
        ] = 1

        dataframe.loc[
            (
                (qtpylib.crossed_below(dataframe[f'k1_{self.buy_ap.value}_{self.buy_coeff.value}']),
                  (dataframe[f'k2_{self.buy_ap.value}_{self.buy_coeff.value}']))
                # (qtpylib.crossed_below(dataframe['k1'] , dataframe['k2']))
                #    (dataframe['k1'] < dataframe['k2']) &
                #    (dataframe['signal'].shift(1) == 'buy')
            ),
            "enter_short",
        ] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (qtpylib.crossed_below(dataframe[f'k1_{self.buy_ap.value}_{self.buy_coeff.value}']),
                  (dataframe[f'k2_{self.buy_ap.value}_{self.buy_coeff.value}']))
                    #(dataframe['k1'] < dataframe['k2']) &
                    #(dataframe['signal'].shift(1) == 'buy')
            ),
            "exit_long",
        ] = 1

        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe[f'k1_{self.buy_ap.value}_{self.buy_coeff.value}']),
                  (dataframe[f'k2_{self.buy_ap.value}_{self.buy_coeff.value}']))
                    #(dataframe['k1'] > dataframe['k2']) &
                    #(dataframe['signal'].shift(1) == 'sell')
            ),
            "exit_short",
        ] = 1

        return dataframe

    def generateAlphaTrend(self, dataframe: DataFrame, ap, coeff):
        df = dataframe.copy()
        
        # atr = "ATR_" + str(ap)
        atr = "ATR"
        df[atr] = ta.SMA(ta.TRANGE(df), timeperiod=ap.value)

        # df[atr] = ta.ATR(df, timeperiod=ap)
        at = 'k1'
        at2 = 'k2'

        noVolumeData = False
        upt = []
        downT = []
        AlphaTrend = [0.0]
        rsi = ta.RSI(df['close'], timeperiod=ap)

        k1 = []
        k2 = []
        signal ='signal'
        mfi = ta.MFI(df, timeperiod=ap)

        print(at)
        for i in range(len(df['low'])):
            if pd.isna(df[atr][i]):
                upt.append(0)
            else:
                upt.append(df['low'][i] - (df[atr][i] * coeff))

        for i in range(len(df['high'])):
            if pd.isna(df[atr][i]):
                downT.append(0)
            else:
                downT.append(df['high'][i] + (df[atr][i] * coeff))

        for i in range(1, len(df['close'])):
            if noVolumeData is True and rsi[i] >= 50:
                if upt[i] < AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                    AlphaTrend.append(upt[i])

            elif noVolumeData is False and mfi[i] >= 50:
                if upt[i] < AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                    AlphaTrend.append(upt[i])
            else:
                if downT[i] > AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                    AlphaTrend.append(downT[i])

        for i in range(len(AlphaTrend)):
            if i < 2:
                k2.append(0)
                k1.append(AlphaTrend[i])
            else:
                k2.append(AlphaTrend[i - 2])
                k1.append(AlphaTrend[i])

        df[at] = pd.DataFrame(data=k1, columns=['k1'])
        df[at2] = pd.DataFrame(data=k2, columns=['k2'])

        conditions  = [ df[at] > df[at2], (df[at] == df[at2]), df[at] < df[at2] ]
        choices     = [ "buy", 'same', 'sell' ]
        df["basic_signal"] = np.select(conditions, choices, default=np.nan)

        # new_C = []
        # for x in df.loc[:, "signal"]:
        #     new_C.append(x if x != "same" else new_C[-1])
        #     print(new_C)
        # df.loc[:, "signal"] = new_C # assign new_C as the new "C" column

        previous = "same"
        for i in range(len(df)):
            if df.loc[i ,"k1"] == df.loc[i ,"k2"]:
                comment = previous
            else:
                comment = "buy" if df.loc[i ,"k1"] > df.loc[i ,"k2"] else "sell"
            df.loc[i ,"signal"] = comment
            previous = comment

        df.fillna(0, inplace=True)
        df.to_csv('df_at.csv', index = False, header=True)

        return df

**Comment by xmatthias** [comment]
`buy_ap: CategoricalParameter([14, 15, 16], default=14, space = "buy", optimize=True, load=True)` (and all similar occurances) are type assignments only (buy_ap will still be None after this line).

you'll need to use `buy_ap = CategoricalParameter([14, 15, 16], default=14, space = "buy", optimize=True, load=True)` in each instance.

**Comment by yazbuz** [comment]
oh ok :) sorry for that. thanks a lot. after that i will use =) instead of :)

**Comment by batuhanhazarguler** [comment]
`
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        alphatrend = self.generateAlphaTrend(dataframe)

        dataframe['k1'] = alphatrend['k1']
        dataframe['k2'] = alphatrend['k2']
        dataframe['signal'] = alphatrend['signal']

        # for elis leverage
        if self.can_use_elis_leverage == True:         
            dataframe['elis'] = alphatrend['elis']

        return dataframe

def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (   
                # (qtpylib.crossed_above(dataframe['k1'] , dataframe['k2']))
                (dataframe['k1'] > dataframe['k2']) &
                (dataframe['signal'].shift(1) == 'sell')
            ),
            'enter_long',
        ] = 1

        dataframe.loc[
            (
                # (qtpylib.crossed_below(dataframe['k1'] , dataframe['k2']))
                (dataframe['k1'] < dataframe['k2']) &
                (dataframe['signal'].shift(1) == 'buy')
            ),
            "enter_short",
        ] = 1

        return dataframe

def generateAlphaTrend(self, dataframe: DataFrame):
        df = dataframe.copy()
        # ap = 14
        ap = self.at_period
        # coeff = 1.4
        coeff = self.at_coeff


        atr = ta.ATR(df['high'], df['low'], df['close'], timeperiod=ap)

        at = 'k1'
        at2 = 'k2'

        noVolumeData = False
        upt = []
        downT = []
        AlphaTrend = [0.0]
        rsi = ta.RSI(df['close'], timeperiod=ap)
        
        k1 = []
        k2 = []
        
        mfi = ta.MFI(df['high'], df['low'], df['close'], df['volume'], timeperiod=ap)


        # print(at)
        for i in range(len(df['low'])):
            if pd.isna(atr[i]):
                upt.append(0)
            else:
                upt.append(df['low'][i] - (atr[i] * coeff))

        for i in range(len(df['high'])):
            if pd.isna(atr[i]):
               downT.append(0)
            else:
              downT.append(df['high'][i] + (atr[i] * coeff))

        for i in range(1, len(df['close'])):
            if noVolumeData is True and rsi[i] >= 50:
                if upt[i] < AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                   AlphaTrend.append(upt[i])

            elif noVolumeData is False and mfi[i] >= 50:
                if upt[i] < AlphaTrend[i - 1]:
                   AlphaTrend.append(AlphaTrend[i - 1])
                else:
                   AlphaTrend.append(upt[i])
            else:
                if downT[i] > AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                    AlphaTrend.append(downT[i])

        for i in range(len(AlphaTrend)):
            if i < 2:
                k2.append(0)
                k1.append(AlphaTrend[i])
            else:
                k2.append(AlphaTrend[i - 2])
                k1.append(AlphaTrend[i])



        df[at] = pd.DataFrame(data=k1, columns=['k1'])
        df[at2] = pd.DataFrame(data=k2, columns=['k2'])

        conditions  = [ df[at] > df[at2], (df[at] == df[at2]), df[at] < df[at2] ]
        choices     = [ "buy", 'same', 'sell' ]
        df["basic_signal"] = np.select(conditions, choices, default=np.nan)


        previous = "same"
        for i in range(len(df)):
          if df.loc[i,"k1"] == df.loc[i,"k2"]:
            comment = previous
          else:
            comment = "buy" if df.loc[i,"k1"] > df.loc[i,"k2"] else "sell"
          df.loc[i,"signal"] = comment
          previous = comment

        if self.can_use_elis_leverage == True:
            elisGenerate = self.elis(dataframe)
            df['elis'] = elisGenerate['elis']
        
        df.fillna(0, inplace=True)
        # df.to_csv('df_at.csv', index = False, header=True)


        
        return df
    ####### calculate AlphaTrend #######


    `
I hope it works. I've been using it for about a year. the profit is pretty low in the strategy I made. I hope you have a better strategy. 👍 :))
