### ISSUE TITLE
has no attribute 'crossed_under'

### ISSUE THREAD

**Issue by remymandmets** [freqtrade/freqtrade-strategies#37]
Hi! 
I have working strategy but if i try to add  EMA I get this error with backtesting and with bot itself. 
I get this error even when i just write it in def populate_indicators.
dataframe['ema20'] = ta.EMA(dataframe, timeperiod=20)
        dataframe['ema50'] = ta.EMA(dataframe, timeperiod=50)
dataframe['ema100'] = ta.EMA(dataframe, timeperiod=100)

and i have tried  with Binance EMAs (7/25/99) but nothing works. 

My entry point is (and where i try to add EMA):
 (dataframe['close'] < dataframe['bb_lowerband'])&
 (dataframe['macd'] < 0)

Can anybody please tell me what i'm doing wrong?
Thanks!!

2019-07-12 17:39:07,182 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2019-06-09T09:45:00+00:00 up to 2019-07-12T13:30:00+00:00 (33 days)..
2019-07-12 17:39:07,197 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/remy2/freqtrade-develop/freqtrade/main.py", line 46, in main
    args.func(args)
  File "/home/remy2/freqtrade-develop/freqtrade/optimize/__init__.py", line 61, in start_backtesting
    backtesting.start()
  File "/home/remy2/freqtrade-develop/freqtrade/optimize/backtesting.py", line 452, in start
    'end_date': max_date,
  File "/home/remy2/freqtrade-develop/freqtrade/optimize/backtesting.py", line 339, in backtest
    ticker: Dict = self._get_ticker_list(processed)
  File "/home/remy2/freqtrade-develop/freqtrade/optimize/backtesting.py", line 223, in _get_ticker_list
    self.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/home/remy2/freqtrade-develop/freqtrade/strategy/interface.py", line 400, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/home/remy2/freqtrade-develop/freqtrade/strategy/default_strategy.py", line 77, in populate_buy_trend
    'buy'] = 1
AttributeError: module 'freqtrade.vendor.qtpylib.indicators' has no attribute 'crossed_under'
remy2@remy2-Vostro-3360:~/freqtrade-develop$

**Comment by hroff-1902** [comment]
crossed_below()

See 
https://github.com/freqtrade/freqtrade/blob/7536f6adbd7706075583b082c39cf2b6688c5652/freqtrade/vendor/qtpylib/indicators.py#L246

**Comment by remymandmets** [comment]
Hi... 
Thank you wory replying.

This is my strategy and as you can see i have nowhere crossed_below on crossed_under :

# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement

import talib.abstract as ta
from pandas import DataFrame

import freqtrade.vendor.qtpylib.indicators as qtpylib
from freqtrade.indicator_helpers import fishers_inverse
from freqtrade.strategy.interface import IStrategy


class DefaultStrategy(IStrategy):
    """
    Default Strategy provided by freqtrade bot.
    You can override it with your own strategy
    """

    # Minimal ROI designed for the strategy
    minimal_roi = {
       
        "0": 0.03
    }

    # Optimal stoploss designed for the strategy
    stoploss = -0.05

    # Optimal ticker interval for the strategy
    ticker_interval = '5m'

    # Optional order type mapping
    order_types = {
        'buy': 'market',
        'sell': 'market',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }


    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe['rsi'] = ta.RSI(dataframe)

        dataframe['adx'] = ta.ADX(dataframe)

        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']

          # MACD
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']


dataframe['ema100'] = ta.EMA(dataframe, timeperiod=100)




        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
               
                (dataframe['close'] < dataframe['bb_lowerband']) &
                (dataframe['macd'] < 0) &
                (dataframe['close'] > dataframe['ema100'])
             
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
 
        dataframe.loc[
            (

(dataframe['close'] > dataframe['bb_upperband'])&
                (dataframe['macd'] > 0)

            ),
            'sell'] = 1
        return dataframe

**Comment by remymandmets** [comment]
If i take EMAs away, everything works fine...

**Comment by hroff-1902** [comment]
Do you have crossed_under in any other file under the user_data or freqtrade directory?

Make 
```
grep -r crossed_under user_data
```
to find all appearences of crossed_under in the user_data directory...

Seems this strategy contains errors (bad identation), when you delete the EMA line it becomes okay and is loaded, otherwise freqtrade searches for same class name and probably finds another file with DefaultStrategy that contains crossed_under()...

It's a bad idea to use DefaultStrategy name for naming your custom strategy. Please assign it a unique name. I hope you have not edited it right in the `freqtrade/strategy/default_strategy.py` file...

**Comment by xmatthias** [comment]
Intendation in the above file looks wrongish to me (could be copy/paste problem - but if it's not then that's the reason).

Depending if you edited the default_strategy object, this may have very odd side-effects

**Comment by hroff-1902** [comment]
Closing it since the question was answered. Feel free to reopen it.
