### ISSUE TITLE
No buys

### ISSUE THREAD

**Issue by poop987** [freqtrade/freqtrade-strategies#44]
I have been running strategy002 for 4 days and still no buys..

**Comment by hroff-1902** [comment]
which exchange and whitelist/blacklist?

**Comment by poop987** [comment]
bittrex

ticker_interval = '5m'

"pair_whitelist": [
            "ETH/BTC",
            "LTC/BTC",
            "ETC/BTC",
            "DASH/BTC",
            "ZEC/BTC",
            "XLM/BTC",
            "NXT/BTC",
            "POWR/BTC",
            "ADA/BTC",
            "XMR/BTC"
        ],
        "pair_blacklist": [
            "DOGE/BTC"
        ]

**Comment by xmatthias** [comment]
Did you backtest the strategy first? 

Most strategies only work in certain market conditions (Strong trend / no trend, ...) or against specific pairs (low volume / high volume), so backtesting a strategy for an extended timeframe (a few months) is highly reccomended to see how the strategy performs in different scenarios.

Also, strategies can behave very differently - from a handfull buys per month to 10s of trades per day.
Backtesting and comparing strategies will give you a good feel for how the strategy will behave.

**Comment by hroff-1902** [comment]
@xmatthias right, in backtesting this strategy has very limited amount of trades, like 28 for 137 days for all pairs:

```
2019-08-30 15:20:18,633 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2019-04-14T18:00:00+00:00 up to 2019-08-30T12:05:00+00:00 (137 days)..
2019-08-30 15:20:18,633 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy Strategy002
Result for strategy Strategy002
========================================================= BACKTESTING REPORT ========================================================
| pair     |   buy count |   avg profit % |   cum profit % |   tot profit BTC |   tot profit % | avg duration     |   profit |   loss |
|:---------|------------:|---------------:|---------------:|-----------------:|---------------:|:-----------------|---------:|-------:|
| ETH/BTC  |           2 |           1.00 |           2.00 |       0.00100000 |           0.67 | 1 day, 10:50:00  |        2 |      0 |
| LTC/BTC  |           1 |           1.00 |           1.00 |       0.00050000 |           0.33 | 4 days, 2:55:00  |        1 |      0 |
| ETC/BTC  |           3 |          -6.63 |         -19.90 |      -0.00997500 |          -6.63 | 2 days, 13:08:00 |        1 |      2 |
| DASH/BTC |           5 |           0.14 |           0.69 |       0.00034347 |           0.23 | 2 days, 10:34:00 |        4 |      1 |
| ZEC/BTC  |           5 |          -1.29 |          -6.46 |      -0.00323750 |          -2.15 | 1 day, 11:24:00  |        4 |      1 |
| XLM/BTC  |           3 |          -6.63 |         -19.90 |      -0.00997500 |          -6.63 | 5 days, 4:57:00  |        1 |      2 |
| ADA/BTC  |           6 |          -2.82 |         -16.91 |      -0.00847500 |          -5.64 | 1 day, 17:06:00  |        4 |      2 |
| XMR/BTC  |           3 |          -2.82 |          -8.45 |      -0.00423750 |          -2.82 | 1 day, 16:50:00  |        2 |      1 |
| TOTAL    |          28 |          -2.43 |         -67.94 |      -0.03405653 |         -22.65 | 2 days, 7:55:00  |       19 |      9 |
========================================================= SELL REASON STATS =========================================================
| Sell Reason   |   Count |
|:--------------|--------:|
| roi           |      19 |
| stop_loss     |       8 |
| force_sell    |       1 |
====================================================== LEFT OPEN TRADES REPORT ======================================================
| pair     |   buy count |   avg profit % |   cum profit % |   tot profit BTC |   tot profit % | avg duration     |   profit |   loss |
|:---------|------------:|---------------:|---------------:|-----------------:|---------------:|:-----------------|---------:|-------:|
| DASH/BTC |           1 |          -5.30 |          -5.30 |      -0.00265653 |          -1.77 | 4 days, 11:30:00 |        0 |      1 |
| TOTAL    |           1 |          -5.30 |          -5.30 |      -0.00265653 |          -1.77 | 4 days, 11:30:00 |        0 |      1 |
```

And this depends on current trends and market conditions. You should probably wait for a couple of weeks till it generates first trade...

**Comment by poop987** [comment]
Great info, I guess it is working correctly and there is probably no issue.
I will keep it going. Thanks.

**Comment by xmatthias** [comment]
@poop987 

> | TOTAL    |          28 |          -2.43 |         -67.94 |      -0.03405653 |         -22.65 | 2 days, 7:55:00  |       19 |      9 |


i'm not sure i would want to do that if you look at the "TOTAL" column above...

This strategy doesn't seem all that profitable (-2% in the last 4 months ...) in current market conditions.

**Comment by poop987** [comment]
@xmatthias No worries I understand, currently I'm just messing around with the running the bot and strategies

**Comment by hroff-1902** [comment]
> @xmatthias No worries I understand, currently I'm just messing around with running the bot and strategies, which one do you suggest?

Hyperopt can help you... Without hyperopt (if you cannot create hyperopt class for choosen strategy), run backtesting for all strategies you are interesting in.
