### ISSUE TITLE
Advice on how to buy according to 24hr %

### ISSUE THREAD

**Issue by joshuar87** [freqtrade/freqtrade-strategies#45]
Hi, I'm hoping someone could give me advice on how to set up a buy sell strategy based on 24hr % change. I.e. buy and sell when price hit's x percent. Is this a relatively easy set up? Thanks!

**Comment by xmatthias** [comment]
getting the pct-change should be as easy as `dataframe['close'].pct_change()`.

You can then shift that (`.shift(X)` - X should be your desired interval - but it's in candles, so it's 24 assuming 1h bars) and compare this historic value with the current value.

sample code ...
``` python
dataframe['pctchange'] = dataframe['close'].pct_change()
dataframe['pctchange24'] = datarame['pctchange'].shift(24 * interval_mins)

## comparions ...
```

**Comment by xmatthias** [comment]
I'll assume this answered. Feel free to reopen if you have additional questions.

**Comment by joshuar87** [comment]
Hi Matthias,

Thanks a lot for the reply. I get this as an example of a pair on the 1m candle. I am finding it difficult to understand why 3 of the candles show as 0 and one + and one -. Also I assume .111 means a 11.1% change over 24hrs? Thanks!

```
                            date          open          high           low         close     volume  pctchange  pctchange24  buy  sell
118793 2020-04-03 11:53:00+00:00  8.000000e-08  8.000000e-08  8.000000e-08  8.000000e-08        0.0        0.0     0.000000    0     0
118794 2020-04-03 11:54:00+00:00  8.000000e-08  8.000000e-08  8.000000e-08  8.000000e-08  2622751.0        0.0     0.000000    0     0
118795 2020-04-03 11:55:00+00:00  8.000000e-08  8.000000e-08  8.000000e-08  8.000000e-08        0.0        0.0    -0.111111    0     0
118796 2020-04-03 11:56:00+00:00  8.000000e-08  8.000000e-08  8.000000e-08  8.000000e-08        0.0        0.0     0.125000    0     0
118797 2020-04-03 11:57:00+00:00  8.000000e-08  8.000000e-08  8.000000e-08  8.000000e-08        0.0        0.0     0.000000    0     0
result for MFT/BTC
```

**Comment by xmatthias** [comment]
well  you get a lot of zeroes because you're using 1m candles on a pair which doesn't have a lot of volume apparently.

If you look at your candles - 4/5 have the volume-column as 0.0. This automatically implies that there was also no change (changes occur when trades happen - which did not happen for this pair).

**Comment by joshuar87** [comment]
Ok I understand thank you. Last question. Is it possible to dry run multiple strategies at once? I've tried with two different config files with different data and etc. but they seem to conflict (including different exchanges).

**Comment by xmatthias** [comment]
yes it is possible - but you need to explicitly specify different databases - otherise the 2 will write into the same database, which obviously is problematic.

**Comment by joshuar87** [comment]
Hi Matthias,

I have tried back testing and my conf & strategy and it seems to run normally. When I do a dry run though there do not seem to be any buy orders though. Even though I will see coins >5% on coinmarketcap and my pair list is set to 200 by volume? Is the shift meant to be - perhaps?

 ```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['pctchange'] = dataframe['close'].pct_change()
        dataframe['pctchange24'] = dataframe['pctchange'].shift(24 * 60)  # shift candles back.

        return dataframe

def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                    (dataframe['pctchange24'] > .05) &
                    (dataframe['pctchange24'] < .22)
            ),
            'buy'] = 1
        return dataframe
```

**Comment by xmatthias** [comment]
well using 24*60 assumes you're using 1m candles - but that'll not work.

in dry-runs you usually get ~498 candles to work with - 24*60 is 1440 - so this may work in backtesting, but it **cannot** work in live / dry.

If you use 5m candles it may work - but then your calculation needs to be aligned to the timeframe used. for 5m candles, it should be `24 * (60 / 5)` (which comes out as 288 candles) ..
