### ISSUE TITLE
Price and Volume strategy

### ISSUE THREAD

**Issue by phantyman** [freqtrade/freqtrade-strategies#6]
## Step 1: What indicators are required?
No need TA indicators.

## Step 2: Explain the Buy Strategy
This is medium frequency strategy. Strategy need 1 second Volume and Price information, and 10s Volume and Price information. Also spread information. Our trigger is  Volume and Price changes for 1s timestamp in % from previous 1s timestamp. In this case bot can trigger in wrong situations than someone sell/buy the whole order book. Our guard is 10s spread decrease. Spread indicator will tell us that currency have real liquidity. We rebuy currency till all that parameters are fine. 

## Step 1: Explain the Sell Strategy
Sell strategy is 0.005 profit in 0-5 mins.  
Force sell -0.001 after 5 mins. 

Thanks.

**Comment by berlinguyinca** [comment]
how will this work with trading fees and that bitrex for example has a min tick of 1 minute. Unless the bot has to collect all the data to the second level

**Comment by Dante2333** [comment]
This can't be implemented on bittrex as they do not provide tick data, maybe there's some way to do this using websockets?

**Comment by xmatthias** [comment]
This can't be implemented on any exchange - as the smallest unit exchanges provide information is usually 1m (or 15s - but FTX stopped providing that too).
