### ISSUE TITLE
TD Sequential indicator  - new strategy

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade-strategies#68]
*For requestion a new strategy. Please use the template below.*  
*Any strategy request that does not follow the template will be closed.*

## Step 1: What indicators are required?
no indicators needed, just close prices

## Step 2: Explain the Buy Strategy

the trigger to buy -> 
When you see 9 consecutive closes “lower” than the close 4 bars prior.
An ideal buy is when the low of bars 6 and 7 in the count are exceeded by the low of bars 8 or 9.

## Step 3: Explain the Sell Strategy
trigger to sell ->
When you see 9 consecutive closes “higher” than the close 4 candles prior.
An ideal sell is when the the high of bars 6 and 7 in the count are exceeded by the high of bars 8 or 9.

## Source
What come from this strategy? Cite your source:
https://hackernoon.com/how-to-buy-sell-cryptocurrency-with-number-indicator-td-sequential-5af46f0ebce1

**Comment by hroff-1902** [comment]
* a good article on this indicator: http://practicaltechnicalanalysis.blogspot.com/2013/01/tom-demark-sequential.html
* a reference page at the tradingview: https://www.tradingview.com/chart/BTCUSD/2MJxxId6-Tom-Demark-Sequential-T-D-Sequential/

(to log it here)

**Comment by xmatthias** [comment]
I guess #75 does fix this?

Let me know if that's not the case ...
