### ISSUE TITLE
README.md links to free trading strategies broken

### ISSUE THREAD

**Issue by metaperl** [freqtrade/freqtrade-strategies#70]
The [section of the README](https://github.com/freqtrade/freqtrade-strategies#free-trading-strategies) listing free trading strategies does not have working links. Instead, the links should point to the files rooted in the repo starting at https://github.com/freqtrade/freqtrade-strategies/tree/master/user_data/strategies

**Comment by xmatthias** [comment]
Thanks, i'll fix the links for this.

Please consider these strategies as samples - 
please do backtesting of a more recent period (and of the pairs you're going to be trading) yourself to make sure the strategy suits your expectations!
