### ISSUE TITLE
How to access previous candle values for strategy?

### ISSUE THREAD

**Issue by dsldsl** [freqtrade/freqtrade-strategies#79]
If i want to create a strategy that would buy whenever an indicator for the current candle is lower than the indicator was 3 days ago, how would I go about that in freqtrade?  

For instance, is the RSI now > the RSI at weekly open.

Thank you v much!

**Comment by dsldsl** [comment]
Also, while I'm asking - I'm figuring out how to access a different TF indicator values while writing a strategy on a different TF.  So, access the RSI for 1h while creating a strategy for 5m.  

I know how to do both of these things with the underlying pandas data, just figuring out the best practice way to do this within the freqtrade framework.

**Comment by xmatthias** [comment]
well - the dataframe you get is just a pandas - so `dataframe['rsi'].shift(3)` is perfectly ok.

Don't use negative offsets, don't use offsets > 499 (these won't be available in real / dry modes).

for the diferent timeframes:
Best look at [the documentation](https://www.freqtrade.io/en/latest/strategy-customization/#example-fetch-live-historical-candle-ohlcv-data-for-the-first-informative-pair).

You can then use [technical](https://github.com/freqtrade/technical#usage) to merge the 2 dataframes and have both things available in one dataframe (for easy comparisons and such).

**Comment by centerdevs** [comment]
What if my main timeframe is 5m, but I need dataframe with 1d frame for the last 30days, how to fetch it and use it in my strategy?

`self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe='1d')`

Returns empty result

**Comment by xmatthias** [comment]
You'll need to make sure it's defined as informative pair combination.

**Comment by centerdevs** [comment]
> You'll need to make sure it's defined as informative pair combination.

Thanks, but it's the same pair. Main dataframe is 1m interval... and I need also the same pair with 1d interval ( for the last 30 days )

**Comment by xmatthias** [comment]
@centerdevs  Please read the [documentation](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs) about features you're trying to use.

Also - please avoid reviving issues that have been solved for multiple months.
