### ISSUE TITLE
Strategy creation

### ISSUE THREAD

**Issue by LightDelphin** [freqtrade/freqtrade-strategies#81]
Hello everyone. 
I try to understand the strategies, I tried to trade on the ready-made ones that you published. But I wonder if I have a chart, then how the strategy code will look on it, in order to try to insert it into the bot.

https://i.ibb.co/12STw4G/photo-2020-05-18-11-04-09.jpg

Maybe someone can share a similar strategy.

Thanks in advance.

**Comment by hroff-1902** [comment]
moved it from main freqtrade repo to freqtrade-strategies, where it better suites I believe...

**Comment by hroff-1902** [comment]
seems it's a request for a strategy utilizing Fibonacci Retracements / Fibonacci Ratios, the technical lib has an appropriate indicator, try to have a look at it first

**Comment by xmatthias** [comment]
Was just going to ask the same - based on the numbers it seems like it's related to fibonacci but i've never seen it drawn like this.

**Comment by LightDelphin** [comment]
Yes. That's right - it's hibonachi. But it’s not entirely clear how to launch a bot according to this strategy, where to start?

**Comment by LightDelphin** [comment]
I installed technical. Where can I read about these fibonacci indicators? Now do these indicators (Fibonacci Retracements / Fibonacci Ratios) write into the strategy?
