### ISSUE TITLE
How to use HyperOpt results in strategy

### ISSUE THREAD

**Issue by MASalem** [freqtrade/freqtrade-strategies#86]
Hello 

I did not where to ask this, but is there any documentation about how to use HyperOpt results inside the strategy I'm trying to optimise? 

Thanks a lot !

**Comment by xmatthias** [comment]
well - [the documentation](https://www.freqtrade.io/en/latest/hyperopt/) ?

**Comment by MASalem** [comment]
I completely missed that part.. Thanks for your help
