### ISSUE TITLE
Error backtesting

### ISSUE THREAD

**Issue by bomberpilot** [freqtrade/freqtrade-strategies#87]
Whenever I backtest the generic strategy file that you create with the installation guide, it works fine. 

However, whenever I try to backtest one of the berlinguyinca strategies, or any other strategy, I am getting the traceback and error shown in the snip. I don't even have the Strategy005 in my files anymore, so why is that tripping a permission error? 

![error snip](https://user-images.githubusercontent.com/35118664/84177606-b177b100-aa48-11ea-949e-967199f12f97.JPG)

**Comment by xmatthias** [comment]
well - best look at the directory the error tells you:
`/home/tyson/freqtrade/user_data/strategies/`

It's most likely a problem with system level permissions (you cloned / copied it with sudo / root - and are now running freqtrade as normal user.

it most likely can be solved by something like `sudo chown tyson: /home/tyson/freqtrade/user_data/ -R` (assuming your user is tyson and you're running it as tyson) - but the file is there otherwise this error should not pop up.

One alternative is that you've got *.pyc / `__pycache__` files in that folder - but i've never seen that cause a problem with loading strategy.

**Comment by bomberpilot** [comment]
Thanks for the quick reply! 
That was my thought too, but in that directory (the user_data/strategies directory), there is no Strategy005 file, and I don't understand why it is trying to get access to that file anyways. There is no mention of Strategy005 in the file I'm trying to backtest (just the ReinforcedSmoothScalp strategy from the Berlinguyinca files). 

I used the sudo chown ..... -R command, but no change in the error message. 

I also get the same error if I copy the only strategy file that seems to backtest, but change only the name and the class_name.

I'm running an ubuntu virtualenv with Python 3.8.

**Comment by xmatthias** [comment]
your best bet might be to remove all `__pycache__` folders...

you can find them using `find . -iname __pycache__`  - and hope it's something to do with caching ...

**Comment by bomberpilot** [comment]
Any other thoughts on this issue? I keep running into it over and over again. 

I have reinstalled freqtrade multiple times, uninstalled and reinstalled Ubuntu multiple times. I updated my Windows Visual Studios and SDK software. 
But still I can run a couple backtests, but then it eventually gives me the Errno 13 and nothing can fix it. This particular time it is for the config.json. If I initialize a new config file, then it will tell me that the Errno is for a strategy file that doesn't exist. 

I have used py3clean . in between almost every backtest because I noticed that the backtest results weren't changing unless I cleared all the cache files, even though I had changed significant parts of the config or strategy.

Fatal exception!                                                                                                 Traceback (most recent call last):                                                                                 File "/home/chief/freqtrade/freqtrade/main.py", line 36, in main                                                   return_code = args['func'](args)                                                                               File "/home/chief/freqtrade/freqtrade/commands/list_commands.py", line 68, in start_list_strategies                config = setup_utils_configuration(args, RunMode.UTIL_NO_EXCHANGE)                                             File "/home/chief/freqtrade/freqtrade/configuration/config_setup.py", line 19, in setup_utils_configuration        config = configuration.get_config()                                                                            File "/home/chief/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config                      self.config = self.load_config()                                                                               File "/home/chief/freqtrade/freqtrade/configuration/configuration.py", line 94, in load_config                     config: Dict[str, Any] = self.load_from_files(self.args.get("config", []))                                     File "/home/chief/freqtrade/freqtrade/configuration/configuration.py", line 73, in load_from_files                 config = deep_merge_dicts(load_config_file(path), config)                                                      File "/home/chief/freqtrade/freqtrade/configuration/load_config.py", line 48, in load_config_file                  with open(path) if path != '-' else sys.stdin as file:                                                       PermissionError: [Errno 13] Permission denied: 'config.json'

**Comment by xmatthias** [comment]
one thing i don't understand - your paths suggest you're using macos/linux - but you mention windows above...

so how's your installation look like in detail?

**Comment by bomberpilot** [comment]
I am using an Ubuntu terminal for Windows.

So everything for freqtrade is contained within the Ubuntu file structure,
and then the virtualenv lives there too.
I swapped to a new username (chief) with the last couple re-installations
to see if that would help.
I thought that I had everything up and running well finally today, but the
first time I went to run an EmptyHyperopt for roi stoploss and trailing, it
gave me the Errno 13 for config.

I remade the config with the new-config command and prompts, then it gave
me errno 13 for the strategy. I deleted the strategy and tried a different
strategy, but still get the same error for the same old strategy that now
doesn’t exist.

Python 3.8.

**Comment by xmatthias** [comment]
which version of WSL are you using? 1 or 2? (2 is only available on the VERY latest version of windows).


When using WSL - you must be careful how you edit and access your files. 
The files are available in native windows programs too (in a subdirectory somewhere) - but editing them this way will mess up and break permissions - so the best is to use WSL - and when editing files, use vim or VSCode (with the WSL extension) - so the files are opened as native linux files.

Also - you might want to exclude this directory from antivirus - it can lock files at certain points - and since .py / .pyc files are executable files, antivirus is .... not always happy to have them there (depending on the antivirus product).

**Comment by bomberpilot** [comment]
Interesting. I have been using Atom as my editor, so maybe the issue lies
there somewhere.

I am not sure about the WSL version. I’ll look into it. I am swapping to my
laptop to see if a fresh install there will work properly.

I have kept my antivirus disabled in regards to freqtrade and python so
that it won’t block them.

Thanks for helping me out and the replies.

**Comment by xmatthias** [comment]
using atom is not wrong - you just need to look out as to how it's accessing the folder (via windows, or via linux api's).
Most editors do it via windows (also vscode, withou the wsl extension).

using a mix is never good, as the permission systems are simply not compatible
