### ISSUE TITLE
Strategy error

### ISSUE THREAD

**Issue by lykslouisa** [freqtrade/freqtrade-strategies#92]
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/68923469/89128503-0fae9680-d4c4-11ea-9f04-860826b24d33.png)

*For requestion a new strategy. Please use the template below.*  
*Any strategy request that does not follow the template will be closed.*

## Step 1: What indicators are required?
*Please list all the indicators required for the buy and sell strategy.*

## Step 2: Explain the Buy Strategy
*Please explain in details the indicators you need to run the buy strategy, then
explain in detail what is the trigger to buy.*

## Step 1: Explain the Sell Strategy
*Please explain in details the indicators you need to run the sell strategy, then
explain in detail what is the trigger to sell.*

## Source
What come from this strategy? Cite your source:
* http://

**Comment by lykslouisa** [comment]
https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/Strategy002.py

**Comment by xmatthias** [comment]
Well the message says it all - Freqtrade can't find the strategy.

please make sure the strategy is in the correct directory ([as documented](https://www.freqtrade.io/en/latest/strategy-customization/#install-a-custom-strategy-file)).

**Comment by polakenfold** [comment]
Same kind of error here
Cant make sample strategies to run on ft

**Comment by xmatthias** [comment]
@polakenfold as mentioned above - ensure that the strategy is in the correct directory - and that you're using the commands as described in the [documentation](https://www.freqtrade.io/en/latest/).

**Comment by lykslouisa** [comment]
I discovered that the error was just a typo. Try using $freqtrade trade -s Simple_strategy. Note the strategy specified should be your “strategy Class” and not the file name of your strategy.
Good luck
