### ISSUE TITLE
Bot doesn't seem to be buying when Close is inferior to the Linear Regression Line - ATR (Dry Run)

### ISSUE THREAD

**Issue by zlac116** [freqtrade/freqtrade-strategies#95]
Hi Team - I would really appreciate your help with this. I have reviewed the code several times to try and determine the issue. Thanks

**Issue**
I have backtested this strategy and had a look at the output dataframe and the buy signals seems to be generated correctly. However, when I run it in dry-run mode the bot seems to buy irrespective of whether the close is inferior to the linear regression line - 1 *ATR. It just seems to sporadically generate buy signals.

I have attached a screenshot from tradeview showing when the bot decided to buy in dry run mode. The black line is the close, blue is the 25 candle linear regression line, red is the upper/lower +/- 1 ATR.

![Screenshot from 2020-08-24 07-29-37](https://user-images.githubusercontent.com/66669459/91013014-f7232f00-e5de-11ea-912e-4c96ccde0a29.png)

What indicators are required?
Linear Regression Angle
Linear Regression Line/Channel
RSI

       **# RSI
        dataframe['rsi'] = ta.RSI(dataframe)

        # Linear Regression Angle
        dataframe['angle'] = ta.LINEARREG_ANGLE(dataframe['close'], timeperiod=5)

        # Linear Regression Line
        dataframe['lr_middle'] = ta.LINEARREG(dataframe['close'], timeperiod=25)
        dataframe['atr'] = ta.ATR(dataframe,timeperiod=25)
        dataframe['lr_lower1.0'] = dataframe['lr_middle'] - dataframe['atr'] * 1**

*Please explain in details the indicators you need to run the buy strategy, then
explain in detail what is the trigger to buy.*

Buy if last 5 candles show a strong downtrend (linear regression angle) and close is inferior to the 25 candle linear regression line - 1 * ATR (over 25 candles)

    **def populate_buy_trend(self, dataframe: DataFrame) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['angle'] < -0.1) &
                (dataframe['close'] < dataframe['lr_lower1.0']) &
                (dataframe['volume'] > 0)
            ),
            'buy'] = 1
        return dataframe**

## Step 1: Explain the Sell Strategy
*Please explain in details the indicators you need to run the sell strategy, then
explain in detail what is the trigger to sell.*

Sell if RSI is greater than 31 and close is superior to the 25 candle linear regression line

    **def populate_sell_trend(self, dataframe: DataFrame) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['rsi'] > 31) &
                (dataframe['close'] > dataframe['lr_middle']) &
                (dataframe['volume'] > 0)
            ),
            'sell'] = 1
        return dataframe**

**Comment by xmatthias** [comment]
i would recommend to use `freqtrade plot-dataframe` to have a plot instead of tradingview.

Tradingview uses certain formulas to calculate things - and ta-lib may or may not use the same - so you're looking at lines in tradingview which may not correspond to the lines ta-lib generates - so while looking at tradingview, the signal seems odd - while in reality, it's correct based on how the lines are calculated by ta-lib.

While most consider tradingview to be "the" implementation - it's not always correctly following the formulas as defined by the original authors.

**Comment by zlac116** [comment]
Thanks for the advice. It seems to be working, according to the backtest results for COMP/USDT. See attached...
![newplot](https://user-images.githubusercontent.com/66669459/91022167-af0b0900-e5ec-11ea-871b-419d32195179.png)
will do the same for the dry-run.
