### ISSUE TITLE
MACD with custom candle stick as a base of calculation?

### ISSUE THREAD

**Issue by kiandp** [freqtrade/freqtrade-strategies#98]
*For requestion a new strategy. Please use the template below.*  
*Any strategy request that does not follow the template will be closed.*

## Step 1: What indicators are required?
#MACD

## Step 2: Explain the Buy Strategy
We will buy when macd crossed_Above macdsignal but we are going to use our tailored macd for this straetgy

## Step 1: Explain the Sell Strategy
We will sell when macdsignal crossed_Above macd, but we are going to use our tailored macd for this strategy

Is it possible to use ("high"+"low")/2) instead of "close" for its calculation?
I tried to define hl2 and then feed this to the macd but it gave me an error.

"hl2 = (dataframe["close"] + dataframe["open"])/2"

&

I tried to change the value inside the macd and I encountered the error again.

" macd = ta.MACD(dataframe,fastperiod=8, slowperiod=28, signalperiod=9)
"
When I change the data frame with close or hl2 it won't work, I know it's not defined and that's why not working.

So is it possible to make our custom values based on our dataset
 cols = ['date', 'open', 'high', 'low', 'close', 'volume']
 and use them as source of calculation ?(like hl2,hlc3,ohlc/4,ema ,.....)
I deeply appreciate your time  & knowledge.

**Comment by xmatthias** [comment]
well, the right place to search for answers related to this would be the [ta-lib](http://mrjbq7.github.io/ta-lib/abstract.html) documentation (this is the link to the python wrapper - but their documentation is better than the original).
TA-Lib is only one of the methods to calculate technical indicators - yes, it's the one Freqtrade uses for most example, but we don't really provide support for it.

---


We're using the "abstract" version of ta-lib - so the correct input should be:

``` python
dataframe['hl2'] = (dataframe["close"] + dataframe["open"]) / 2
macd = ta.MACD(dataframe,fastperiod=8, slowperiod=28, signalperiod=9, price='hl2')
dataframe['macd'] = macd['macd']
dataframe['macdsignal'] = macd['macdsignal']
dataframe['macdhist'] = macd['macdhist']
```

**Comment by kiandp** [comment]
Thanks, @xmatthias.
